### ISSUE TITLE
feature request: add license to binary tarball

### ISSUE THREAD

**Issue by draptik** [remotemobprogramming/mob#105]
While setting up the arch package `mobsh-bin` I had to download the LICENSE file manually because it is not included in the binary tarball https://github.com/remotemobprogramming/mob/releases/download/v1.1.0/mob_v1.1.0_linux_amd64.tar.gz (it currently only includes the `mob` binary).

Since this is my first arch package I asked for feedback in the arch forum: https://bbs.archlinux.org/viewtopic.php?pid=1947520#p1947520

eschwartz, an experienced arch user, gave me this advice:

> Usually one would wish the LICENSE file to be shipped in the binary tarball, consider opening an upstream bug.

It seems to be common / good practice to include a license file in binary tarballs. From https://wiki.archlinux.org/index.php/PKGBUILD

> Mandatory variables are [...]. `license` is not strictly necessary to build a package, but is recommended for any `PKGBUILD` shared with others, as *makepkg* will produce a warning if not present.

Is it possible to include the LICENSE file in the binary tarball in upcoming releases?

**Comment by simonharrer** [comment]
Makes sense. Interested in helping out? The GitHub Actions build the packages and would need to be changed for that so they include the LICENSE in the targz files.

**Comment by draptik** [comment]
Sorry, I'm not that firm with Github Actions yet. 
F.ex. I am not sure if I have to setup things like Secrets etc to get something like this up and running in my fork...

**Comment by draptik** [comment]
Maybe it's sufficient to replace L35 in https://github.com/draptik/mob/blob/master/.github/workflows/release.yaml?

Before:

```yaml
file: "*{.tar.gz,_checksum.txt}"
```
After:

```yaml
file: "*{.tar.gz,_checksum.txt,LICENSE}"
```

Completely untested, just guessing ;-)

**Comment by simonharrer** [comment]
Not sure. Maybe the GitHub Action plugin that’s being used should be looked at.

**Comment by simonharrer** [comment]
I had a look, the https://github.com/remotemobprogramming/mob/blob/master/.github/build is responsible for creating the .tar.gz file. As far as I understand it, you want to have the LICENSE file inside the .tar.gz file, right? If so, one would need modify this shell script at `.github/build` to add it.

**Comment by draptik** [comment]
Thanks for finding the correct location to change!
I'll create a pull request.

**Comment by simonharrer** [comment]
Not sure, however, what the install procedure now will do at https://github.com/remotemobprogramming/mob/blob/master/install.sh#L111 with the additional file available. In the worst case scenario, we would add a license file to /usr/local/bin/. We should make sure this won't happen. Can you have a look at how we can prevent that?

**Comment by draptik** [comment]
The install.sh script already does everything correctly:

```sh
curl -sSL "$url" | tar xz -C "$target" "$(determine_mob_binary)" && chmod +x "$target"/mob
```

The part `curl ... | tar xz -C "$target" "$(determine_mob_binary)"`  only extracts the binary, so other files (i.e. LICENSE) are not extracted to the target location.

**Comment by simonharrer** [comment]
Thanks for verifying that! I'll close the ticket as it's done.

Thanks again for making this feature happen.
