### ISSUE TITLE
Mob start/next throws when a hyphen is included in the branch name

### ISSUE THREAD

**Issue by zdhz** [remotemobprogramming/mob#117]
Hello 👋 

Version: v1.1.0

First of all, thanks for creating this tool - it's been super useful for our team!

Since upgrading to v1, an error is thrown when including a hyphen (-) in our WIP branch name. When calling the following:

```
mob start -b test-branch
mob next
```

An error is thrown:

```
 ERROR git --no-pager log master-test..mob/master-test-branch --pretty=format:%an --abbrev-commit
 ERROR fatal: ambiguous argument 'master-test..mob/master-test-branch': unknown revision or path not in the working tree.
 ERROR Use '--' to separate paths from revisions, like this:
 ERROR 'git <command> [<revision>...] -- [<file>...]'
 ERROR exit status 128
```

On first glance it looks like the hyphen is causing some function to interpret the base branch as `master-test` instead of `master`.

It's a minor issue, but helpful when naming our branches against JIRA tickets 😄 

Thanks

**Comment by simonharrer** [comment]
Thanks for reporting the bug. I'll have a look in the next few days.

**Comment by gregorriegler** [comment]
Taking a look now @simonharrer

**Comment by simonharrer** [comment]
https://github.com/remotemobprogramming/mob/commit/7dacd9242949ee26ec714328f9bf64d91632e385 reverted merge of the PR so tests are green again. This means, this bug is still open.

**Comment by gregorriegler** [comment]
will check as soon as I have time.
I know that I ran all the tests with my IDE, and that all the GitHub checks
passed too.

Gregor Riegler
gregorriegler.com


Am So., 31. Jan. 2021 um 11:54 Uhr schrieb Simon Harrer <
notifications@github.com>:
