### ISSUE TITLE
Sound output sometimes not working on windows

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#119]
We had issues with the sound output of mob. Hypothesis: if cortana is disabled it doesn’t work anymore. But that’s not verified.

**Comment by felixbutton** [comment]
I enabled cortana again and made sure it's able to speak. Still no sound on "moo" or "next" unfortunately (Win10 64bit)

**Comment by simonharrer** [comment]
Can you run 

```
(New-Object -ComObject SAPI.SPVoice).Speak("moo")
```

in your powershell?

**Comment by felixbutton** [comment]
yep, that's working

**Comment by simonharrer** [comment]
Mob basically executes this command like this:

First, it starts a powershell which will start another powershell that executes that actual command in the background.

```
powershell -command "start-process powershell -NoNewWindow -ArgumentList '-command \"(New-Object -ComObject SAPI.SPVoice).Speak(\\"moo\\")\"'"
```

Does this work on your machine?

**Comment by felixbutton** [comment]
Nope, an error is returned (FullyQualifiedErrorId : MissingEndParenthesisInMethodCall). If I remove the backslashes at the end and in the "moo"-brackets it works just as before, then returns 1.
`powershell -command "start-process powershell -NoNewWindow -ArgumentList '-command \"(New-Object -ComObject SAPI.SPVoice).Speak("moo")"'"`

**Comment by simonharrer** [comment]
mob ignores any return code, so that should not be it. 

Can you run ` mob moo --debug` and paste the console log here?

**Comment by felixbutton** [comment]
```
PS C:\Users\Felix> mob moo --debug 
 DEBUG command 'moo'
 DEBUG parameters ''
 DEBUG version 1.1.0
 DEBUG workingDir
 DEBUG Operating System windows
 DEBUG Starting command powershell -command start-process powershell -NoNewWindow -ArgumentList '-command "(New-Object -ComObject SAPI.SPVoice).Speak(\"moo\")""'
 > moo
```

**Comment by simonharrer** [comment]
Hm, so we have a working version and the one of the tool:

```
# working
powershell -command "start-process powershell -NoNewWindow -ArgumentList '-command \"(New-Object -ComObject SAPI.SPVoice).Speak("moo")"'"
# in tool but failing
powershell -command start-process powershell -NoNewWindow -ArgumentList '-command "(New-Object -ComObject SAPI.SPVoice).Speak(\"moo\")""'
```

Seems like the escaping of the strings is the only difference.

**Comment by simonharrer** [comment]
I might have found the issue: https://github.com/remotemobprogramming/mob/tree/fix-119 

Can you checkout that branch and build mob locally and run it to check if it works?

**Comment by felixbutton** [comment]
Yep, that worked!

**Comment by simonharrer** [comment]
great. Maybe this already is the fix. I'll release it today.

**Comment by simonharrer** [comment]
Can you install 1.2.0 to check if it works now?

**Comment by felixbutton** [comment]
Still works. Only other thing is the voice, which is probably the systems default voice (and not the deep male voice which the mac using colleagues had)

**Comment by simonharrer** [comment]
I see. But I would leave that for another issue.
