### ISSUE TITLE
"No such device or address" on mob next

### ISSUE THREAD

**Issue by TobseF** [remotemobprogramming/mob#125]
## Problem
After calling `mob next`, mob commits my changed files and tries to push these. But the push fails with the following error message:
```bash
mob next
   git add --all
   git commit --message mob next [ci-skip] --no-verify
 ERROR git push --no-verify origin mob/main
 ERROR bash: /dev/tty: No such device or address
 ERROR error: failed to execute prompt script (exit code 1)
 ERROR fatal: could not read Username for 'https://github.com': No such file or directory
 ERROR exit status 128
```
So I have to push the `mob/main` branch by hand. This works in command line with the mentioned `git push --no-verify origin mob/main` without any problems.

## Environment
**System**: Windows 10 x64
**Git**:  version 2.30.0.windows.1 
       (available on PATH)
**Mob**: v1.2.0
          (Also tested with v1.1.0)
**Bash**:  C:\Windows\System32\cmd.exe
          (default one)

It seems that `mob` thinks it runs on a Unix system -right? Maybe it has something to do with my  installed _Windows Subsystem for Linux_ (WSL 2).

**Comment by simonharrer** [comment]
Thanks for reporting this. 

Can you run the failing `mob next` command with the `--debug` flag like so `mob next --debug` and give the output here, pelase?

Does it still fail when you run the command in the Git Bash?

**Comment by TobseF** [comment]
This is the debug output with the `cmd.exe`:
```bash
C:\Users\tobse\IdeaProjects\training\swk\2021-02-11-musa-client>mob next --debug
 DEBUG command 'next'
 DEBUG parameters ''
 DEBUG version 1.1.0
 DEBUG workingDir
 DEBUG Running command git rev-parse --abbrev-ref HEAD
 DEBUG mob/main
 DEBUG Running command git branch --format=%(refname:short)
 DEBUG main
 DEBUG mob/main
 DEBUG on currentBranch mob/main => BASE main WIP mob/main with allLocalBranches main,mob/main
 DEBUG current branch mob/main and currentWipBranch mob/main
 DEBUG Running command git rev-parse --abbrev-ref HEAD
 DEBUG mob/main
 DEBUG Running command git branch --format=%(refname:short)
 DEBUG main
 DEBUG mob/main
 DEBUG on currentBranch mob/main => BASE main WIP mob/main with allLocalBranches main,mob/main
 DEBUG Running command git status --short
 DEBUG M src/test/java/rgbledring/FailingTest.java
 DEBUG Running command git add --all
 DEBUG
   git add --all
 DEBUG Running command git commit --message mob next [ci-skip] --no-verify
 DEBUG [mob/main ac08c02] mob next [ci-skip]
 DEBUG  1 file changed, 2 insertions(+), 2 deletions(-)
   git commit --message mob next [ci-skip] --no-verify
 DEBUG Running command git diff HEAD^1 --stat
 DEBUG src/test/java/rgbledring/FailingTest.java | 4 ++--
 DEBUG  1 file changed, 2 insertions(+), 2 deletions(-)
 DEBUG Running command git push --no-verify origin mob/main
 DEBUG bash: /dev/tty: No such device or address
 DEBUG error: failed to execute prompt script (exit code 1)
 DEBUG fatal: could not read Username for 'https://github.com': No such file or directory
 ERROR git push --no-verify origin mob/main
 ERROR bash: /dev/tty: No such device or address
 ERROR error: failed to execute prompt script (exit code 1)
 ERROR fatal: could not read Username for 'https://github.com': No such file or directory
 ERROR exit status 128
````

But you are right. It works when I run it with the git bash.
For now it seems to be more practical to push it by my own, than switching to the _Git Bash_.

**Comment by TobseF** [comment]
My workaround for now:
I changed the _Terminal_ in IntelliJ to the _Git Bash_ (`C:\Program Files\Git\bin\sh.exe`)

**Comment by simonharrer** [comment]
Have a look at https://github.com/atom/atom/issues/8984 there are a few ideas on how to fix this. Perhaps one helps in your case.

**Comment by TobseF** [comment]
Many thing are mentioned in this thread. And the
```bash
git config --global credential.helper wincred
```
did the job!

**Comment by simonharrer** [comment]
Happy to help. :-)

And of course: happy mob programming!
