### ISSUE TITLE
[ci-skip] vs. [skip ci]

### ISSUE THREAD

**Issue by lindt** [remotemobprogramming/mob#126]
when I mob within an azure devops repository, then I need to switch the mob next message to "[skip ci]". Once I forget this, my CI pipeline will be triggered for every "mob next".
Would it be possible to check if the git repository is a azure devops repository and in such a case replace the default "[ci-skip]" with a "[skip ci]" commit message?

How to detect azure devops repositories? A first shot would be if it matches the following patterns.
 - git@ssh.dev.azure.com:v3
 - https://SPECIFIC_PROJECT@dev.azure.com

Would love to hear if this is a feasible approach or what else could be done to mob smooth in azure devops repos.
Thanks.

**Comment by simonharrer** [comment]
You can set the git commit message via an environment variable system wide.

```
# Before
MOB_WIP_COMMIT_MESSAGE=mob next [ci-skip]

# After
MOB_WIP_COMMIT_MESSAGE=mob next [ci-skip] [skip ci]
```

Does this help?

I'm against putting a detection algorithm for the repo location in mob. We can, however, talk about the default MOB_WIP_COMMIT_MESSAGE.

**Comment by lindt** [comment]
but when I set a system wide environment variable, I would need to distinguish between azure devops repos and others.
would like to have a solution where I would not need to think about this.....and just could "mob next" in every repo.

**Comment by simonharrer** [comment]
The default MOB_WIP_COMMIT_MESSAGE will now be `mob next [ci-skip] [ci skip] [skip ci]` so it works on azure DevOps as well.

**Comment by simonharrer** [comment]
Part of next release.
