### ISSUE TITLE
scoop latest version 1.1.0

### ISSUE THREAD

**Issue by csdepop100** [remotemobprogramming/mob#128]
Hi everyone,
I wanted to update my mob version to 1.2.0. using scoop but scoop is telling me, 1.1.0 is the latest version.
Is this intended?
Thanks in advance
![ScoopMob](https://user-images.githubusercontent.com/49524272/108547047-44f8c580-72ea-11eb-8651-32fd2783b73c.png)

**Comment by simonharrer** [comment]
@WtfJoke can you help here, please?

**Comment by WtfJoke** [comment]
Hi @csdepop100 

I cant reproduce the error.
```
scoop update mob
mob: 1.2.0 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

Could it be that, you installed the "old" scoop manifest, which was previously located in this repo.
Can you show the manifest youre installed.
E.g 
`scoop info`

```
Description: Swift git handover with mob
Version: 1.2.0
Website: https://mob.sh
License: MIT (https://spdx.org/licenses/MIT.html)
Manifest:
  C:\Users\USER\scoop\buckets\main\bucket\mob.json
Installed:
  C:\Users\USER\scoop\apps\mob\1.2.0
Binaries:
  mob.exe
```
How does your manifest (json) look like?


If in doubt, just also can do

````
scoop ùninstall mob
scoop install mob
````

**Comment by csdepop100** [comment]
`scoop info` gave me the same output it gave you. Reinstalling helped... I feel IT-supported right now 😀 "Did you try turning it off and on again?". 😀 Thank you very much!
