### ISSUE TITLE
tests fail with version 1.3

### ISSUE THREAD

**Issue by draptik** [remotemobprogramming/mob#134]
While trying to package mob v1.3 from source I encounter the following error:

```sh
go: cannot find main module; see 'go help modules'
==> ERROR: A failure occurred in check().
    Aborting...
```

Building from source is ok.
But running tests currently fails.

```sh
# ....
Creating test assets...

Root of temporary test assets: /tmp/mob
Path to central repository ('remote'): /tmp/mob/remote
Path to clone of central repository ('local'): /tmp/mob/local

Creating test repositories...
Initialized empty Git repository in /tmp/mob/remote/
Cloning into '.'...
warning: You appear to have cloned an empty repository.
[main (root-commit) 4281c7e] initial import
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt
To file:///tmp/mob/remote
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.

Creating a second mob participant's repository...
Path to second clone of central repository ('localotherdir'): /tmp/mob/localother
Cloning into '.'...
Done.
go: cannot find main module; see 'go help modules'
==> ERROR: A failure occurred in check().
    Aborting...
```

Has running the tests changed in this release?

My build steps currently are:

```sh
./create-testbed # <- no error
go test # <- this throws the error message
```

Details:
- https://github.com/draptik/arch-package-builds/blob/ac89004c00297f6c39724a346c2af917e55d4d4f/mobsh/PKGBUILD#L31
- https://github.com/draptik/arch-package-builds/blob/ac89004c00297f6c39724a346c2af917e55d4d4f/mobsh/PKGBUILD#L34

I have also tried compiling the main branch as described in the README. It returns the same error.

Did I miss something obvious?

**Comment by simonharrer** [comment]
make sure you have go 1.15. It fails with go 1.16.

**Comment by draptik** [comment]
Ok, thanks for the feedback. I'll have to put the source package on hold then, because Arch is a rolling release version (I can't easily use an outdated version of go).
I can still package the prebuild binaries though.
Fun fact: v1.2 already worked with go 1.16...

**Comment by draptik** [comment]
For now I excluded the "test" step for v1.3 (I figured if your test suite passes, I don't have to execute the tests for packaging). AUR packages are up-to-date:
https://aur.archlinux.org/packages/?K=mob-programming&SB=p

**Comment by simonharrer** [comment]
go 1.16 support is in the roadmap. Haven’t been able to figure out a way to get go modules working...
