### ISSUE TITLE
maintainer arch/linux wanted

### ISSUE THREAD

**Issue by draptik** [remotemobprogramming/mob#135]
I would like to pass the arch/linux build to somebody smarter. Best: a robot.
As long as the tool sticks to "simple go, and has some tests" it can easily be deployed to Arch via the binary-build.
Happy case for future script: version number bumb.
Worst case: Arch Linux doesn't have a package

My notes:
https://github.com/draptik/arch-package-builds

**Comment by draptik** [comment]
The "robot" would need my credentials for
https://aur.archlinux.org/packages/?K=mob-programming&SB=p

**Comment by Morl99** [comment]
I think that should be straightforward. This repository already contains GitHub Actions to publish to GitHub Releases and to Homebrew (for mac builds). While I have no experience with it, I believe this could be the way to go: 
https://github.com/marketplace/actions/publish-aur-package

The simplest thing to do is to migrate the mobsh-bin PKGBUILD into this repository, so it is available during the release process. This of course means, that the maintainers of this repo would want that to happen.

The more convulated approach would be to create the GitHub Action in your arch-package-builds repo, and to trigger it from the release flow of the mob repository (see https://github.community/t/triggering-by-other-repository/16163 for example). There are probably a multitude of other approaches, like scheduling a job that regularly checks for new releases...

Let me know If I can be of any help with this, and which way sounds good for you and @simonharrer

**Comment by simonharrer** [comment]
A GitHub action makes sense as part of the release process. Feel free to contribute here.

**Comment by draptik** [comment]
@Morl99 feel free to contact me about arch credentials

**Comment by draptik** [comment]
where would be an appropriate place for PKGBUILD in this repo?

**Comment by simonharrer** [comment]
the github actions are living in .github/workflows and the package scripts I would put in .github

**Comment by simonharrer** [comment]
Do arch linux users prefer the build themselves or install a binary? I would like to add one install command to the general install info block. But not sure which one makes more sense.

**Comment by draptik** [comment]
to be honest: I don't know, but the easiest solution would be to only provide a binary.

**Comment by draptik** [comment]
https://aur.archlinux.org/packages/?K=mob-programming&SB=p
mobsh can redirect to mobsh-bin in the description

**Comment by simonharrer** [comment]
So I just add the bin install command to the main install section?

**Comment by draptik** [comment]
@simonharrer sorry, I can't parse your last comment: what is the `bin install` command, and which `main install section` do you mean?

**Comment by simonharrer** [comment]
Have a look at https://github.com/remotemobprogramming/mob/blob/main/README.md#how-to-install

Should I recommend installing from binary or from source there? I only want to provide one option in the 'how to install' section, as I like to keep this section as short as possible.

**Comment by draptik** [comment]
Now I understand... 
Yes, this is correct: We should only support the `mobsh-bin` version.

**Comment by draptik** [comment]
@Morl99 

> where would be an appropriate place for PKGBUILD in this repo?

**Comment by Morl99** [comment]
> @Morl99
> 
> > > The simplest thing to do is to migrate the mobsh-bin PKGBUILD into this repository, so it is available during the release process. This of course means, that the maintainers of this repo would want that to happen.
> 
> > where would be an appropriate place for PKGBUILD in this repo?

I did not answer, because @simonharrer already gave an answer.

> the package scripts I would put in .github

Let me know how I can help with that.

**Comment by simonharrer** [comment]
with release 1.4.0 there might be a additional motivation to get this automated, perhaps. :-)

**Comment by draptik** [comment]
I already published the 1.4 binary to https://aur.archlinux.org/packages/mobsh-bin/

I don't have any experience with the combo "github-actions" and "AUR" and currently don't have the time to investigate.

**Comment by simonharrer** [comment]
@Morl99 would you like to create a PR that automates this process? If so, feel free to do so.

**Comment by draptik** [comment]
manually published 1.5 binary to https://aur.archlinux.org/packages/mobsh-bin/

**Comment by Morl99** [comment]
That does sound about right. I decided, that I will not create a PR for this, since I really don't know anything about Arch Linux. But I am happy to help anybody that wants to tackle this with the aspects of the github action that is needed to do this. Secrets need to be added by @simonharrer, I am sure he will do so if we can point him into the correct direction.

Developing/testing of the action for this can be done in a fork, that is also a place where you could put the secret for the time being. Once everything is in place, you can hand it over to simon.

One little thing I would change in your workflow: I would not actually commit the PKGBUILD, but rather include a template, that is resolved during the build. That saves us from commiting changes during the workflow, which is something that could create problems downstream and also creates unnessecary commits. At least that is what I am doing in all my npm projects with the package.json (which also contains version information for the npm registry).

**Comment by simonharrer** [comment]
I'm happy to help. Just let me know which secrets I should add. :-)

**Comment by gregorriegler** [comment]
I am running arch linux as of recently, but I am not an expert. I'm interrested to learn more however, so I am happy to help too, pairing / mobbing would be fun.

**Comment by seanpoulter** [comment]
Thanks for all the suggestions @Morl99! Would you want to try to pair / mob? If yes, should we reach you through Twitter?

@gregorriegler, I'm also game to try pairing / mobbing since I'm pretty new to this. It would help everyone have confidence when it comes time for code review. Should we find a time that works using Doodle or something similar? 🤔 

I'm new to all of this as well and am happy to collaborate. I'm motivated to learn about GitHub Actions and help reduce the maintenance overhead.

I'll try to connect @draptik and @simonharrer to get the secrets we'll need. :)

We should also figure out if we want to run `namcap` to test the AUR package. It is recommended in the notes but I didn't see it used in [publish-aur-package](https://github.com/marketplace/actions/publish-aur-package). They've got some good [examples](https://github.com/KSXGitHub/parallel-disk-usage/blob/master/.github/workflows/deploy.yaml#L402-L428) of the workflows though. 😁

**Comment by gregorriegler** [comment]
I'm flexible in the coming two days. Monday is a holiday here. I'm in vienna, so my timezone is CET.

**Comment by draptik** [comment]
I am more than happy to add the aur secrets to this projects.
Just give me instructions ;-)

**Comment by draptik** [comment]
I currently maintain this branch manually.

https://aur.archlinux.org/packages/mobsh-bin/

**Comment by draptik** [comment]
I have no idea how to handover a key, and make it, well work for a project.
I don't want to handover my general arch-key.
Somebody has to watch the key transfer ?

**Comment by Morl99** [comment]
Thanks for reaching out. In general I would be open to mob on this. But at the moment, my calendar is too full already. But I'd be happy to review anything you come up with. Alternatively feel free to spontaneously shout out with a twitter dm if you want to work on it, if I am in the mood, I might join you.

**Comment by draptik** [comment]
https://aur.archlinux.org/packages/mob-bin/
somebody else has taken offer. Great: Thank you!

**Comment by draptik** [comment]
but it failed...

**Comment by draptik** [comment]
How is 
![image](https://user-images.githubusercontent.com/313058/139560001-c3aca96c-82db-4457-96cd-2450e357d598.png)

**Comment by draptik** [comment]
I dont care who can publish. Anybody it seems.

I thought I had same Creds for Arch. Obviously everybody can publish to Aur. So you don't need my key. I'm out.

**Comment by seanpoulter** [comment]
Hold on @draptik, I think we still need your help. https://aur.archlinux.org/packages/mob-bin/ is different package. It is missing the `sh`. 

These two are still yours `mobsh` and `mobsh-bin` look like they're still yours:
https://aur.archlinux.org/packages/?O=0&SeB=nd&K=mobsh&outdated=&SB=n&SO=a&PP=50&do_Search=Go

I thought we'd need your credentials based on the initial conversation but we won't need your secrets after all. It looks like we have two options - you'd need to add a co-maintainer for the packages or disown the package and we'll pick it up. This is from the docs (https://wiki.archlinux.org/title/User:Quequotion/AUR_submission_guidelines#Maintaining_packages):

> - Additional maintainers can be added to or removed from a package by clicking "Manage Co-Maintainers" under "Package Actions" on the right of its AUR page and editing the list.
> - If you do not want to continue to maintain the package for some reason, disown the package by clicking "Disown package" under "Package Actions" on the right of its AUR page and/or post a message to the AUR Mailing List. If all maintainers of an AUR package disown it, it will become an "orphaned" package.
> - Orphaned packages can be adopted by clicking on the "Adopt Package" link under "Package Actions" on the right of its AUR page or by pushing to the orphaned repository.

--

@simonharrer, would you like to make an account or should "we" handle it for now?

**Comment by simonharrer** [comment]
I would suggest that @draptik adds me and whoever also wants to help out (@seanpoulter  for example) as co-maintainers of the aur packages. Then we can do everything ourselves from there. What do you think?

**Comment by simonharrer** [comment]
I've just created an account with username 'simonharrer'. I think @draptik you should be able to add me as a co-maintainer with this ID.

**Comment by draptik** [comment]
I'll try to add co-maintainers by the end of the week..

**Comment by draptik** [comment]
@simonharrer you are now co-maintainer

**Comment by simonharrer** [comment]
@seanpoulter I do have access now. Can you guide me which secrets I need to add?

**Comment by seanpoulter** [comment]
Thanks @draptik!

@simonharrer, I don't know which secrets but we'll find out soon. Do you have a preference between using the existing action mentioned above that _may_ not be as defensive, or write our own? Either way I'll commit to support either going forwards. It's the least I can do for `mob`. 😁 

Sorry for the delayed reply @Morl99. I'm in the Eastern timezone so there's a 6h gap. I'll send you a DM to coordinate.

**Comment by WtfJoke** [comment]
> Can you guide me which secrets I need to add?
> I don't know which secrets but we'll find out soon

I guess all these 😄 
```yaml
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
```

Whats probably missing is that one of your newly joined maintainers of the aur package creates an ssh key and put the private key into the secrets as well as the other stuff.

**Comment by simonharrer** [comment]
I've created AUR_USERNAME, AUR_EMAIL and AUR_SSH_PRIVATE_KEY as secrets in this repository. Hope this helps. :-)

**Comment by seanpoulter** [comment]
Thanks @WtfJoke. That is a really interesting idea to keep it simple and push. 🤔 

Thanks for adding the credentials @simonharrer. Do you have a preference for how to generate a file? I'd assume you'd want to write with Go and add a unit test? 😁

**Comment by seanpoulter** [comment]
@simonharrer, you good with not committing the PKGBUILD files to the repo?

**Comment by simonharrer** [comment]
I'm good with any working solution that automates this build process. :-)

**Comment by seanpoulter** [comment]
@draptik, should we publish both packages for the binary and the sources?

**Comment by draptik** [comment]
@seanpoulter 
start with the *bin. 
If that works, try the source, but be ready for surprises.

**Comment by draptik** [comment]
@seanpoulter 
I think there is no reason for a "non"-bin arch package.
I gave up on that long ago.

**Comment by seanpoulter** [comment]
In that case I think we're almost done. 🤞

**Comment by draptik** [comment]
@seanpoulter trust me, you don't want to deal with bleeding edge go compile errors..

**Comment by draptik** [comment]
Give me a heads-up when I can test the arch install ;-)

**Comment by seanpoulter** [comment]
It looks like @simonharrer ran the manual trigger with [this action](https://github.com/remotemobprogramming/mob/runs/4199105437?check_suite_focus=true). @draptik, you can try to install v2.1.0:

![image](https://user-images.githubusercontent.com/2585460/141658102-dd1ca130-e034-4bec-9eca-8b29aed18673.png)

**Comment by draptik** [comment]
Installing v2.1.0 works fine: Great work!

**Comment by simonharrer** [comment]
@seanpoulter can you enable it for the upcoming releases? Then, we can close this, I think.

@draptik would it make sense to delete the source built package, as we will not maintain it anyway?

**Comment by draptik** [comment]
@simonharrer the current process for deleting a package from AUR seems to be:
- "disown" the package
- once all owners have disowned the package it will become "orphaned"
- at this state a request to the AUR mailing list can be made to delete the package

https://wiki.archlinux.org/title/AUR_submission_guidelines#Maintaining_packages

**Comment by simonharrer** [comment]
I disowned https://aur.archlinux.org/packages/mobsh/

**Comment by draptik** [comment]
OK, so did I.
I'll reach out to the mailing list to request the deletion of the package.

**Comment by draptik** [comment]
waiting for reply... (https://bbs.archlinux.org/viewtopic.php?pid=2003596#p2003596)

**Comment by seanpoulter** [comment]
> @seanpoulter can you enable it for the upcoming releases? Then, we can close this, I think.

I'll assume you want to remove the manual trigger too. See #215.

**Comment by simonharrer** [comment]
Thank you all for helping out! Open source at its best! :-)

**Comment by draptik** [comment]
AUR now has only one repo for mob: The binary from here.

![image](https://user-images.githubusercontent.com/313058/142115144-f7c8b65f-b57d-40bc-a471-e074d0b39b20.png)

**Comment by seanpoulter** [comment]
Thank you all for the excellent collaboration! 👏

**Comment by gregorriegler** [comment]
Thank you sean for driving all this. I was gonna write 'thank you for rocking the boat', but now I'm glad I used a translator beforehand, to learn that it means the opposite of what I was trying to say 😅
