### ISSUE TITLE
call os.TempDir() instead of using /tmp/mob in test cases

### ISSUE THREAD

**Issue by stevegt** [remotemobprogramming/mob#149]
We should have mob_test.go call os.TempDir() and pass the resulting pathname to create-testbed, instead of create-testbed using the hardcoded `/tmp/mob`.  See https://github.com/remotemobprogramming/mob/pull/144#issuecomment-802340229 for some background -- in that case, re-using `/tmp/mob` actually caused tests to pass when they should have failed.

We can't simply `rm -rf /tmp/mob` ourselves in create-testbed, because that's a bit risky, particularly since a bunch of people would normally `git clone https://github.com/remotemobprogramming/mob /tmp/mob` for a test drive before installing.

**Comment by simonharrer** [comment]
I second this. I think the fastest way would be to add a parameter to the testbed script to pass in the base directory and default to `/tmp/mob` if it's not there. We can then pass in a temporary folder created within the go tests, maybe even a temporary folder for each test itself.

**Comment by simonharrer** [comment]
t.TempDir is the way to go in the tests. Done that in https://github.com/remotemobprogramming/mob/commit/7c90520084e15bcca0b69120b2e4ec015d89673c
