### ISSUE TITLE
Configurable mob branch name

### ISSUE THREAD

**Issue by OskarD** [remotemobprogramming/mob#15]
If you are multiple mobs working on the same code base, but on different features, there will be conflicts because they are working on the same mob branch. Adding a parameter to the configuration with a branch name for the mob would solve this :)

**Comment by simonharrer** [comment]
You can already do this through an environment variable like this:

```bash
$ MOB_WIP_BRANCH=mob-session mob next # default value
$ MOB_WIP_BRANCH=mob-ticket-42-session mob next # custom value
```

Does this already solve your problem? Or did you had something else in mind?

**Comment by OskarD** [comment]
That solves it! Thank you
