### ISSUE TITLE
Improve support for a micro-commit workflow

### ISSUE THREAD

**Issue by gregorriegler** [remotemobprogramming/mob#153]
Hi,

I would like to work on improving mob.sh, so that it supports a micro-commit workflow better. 

**What is a micro-commit workflow?**
In a micro-commit workflow, developers commit very often while keeping the code working at every commit. A commit could contain a tiny refactoring step or a small increment that adds a tiny bit of test- and production code. When a mob uses a micro-commit workflow, it is common for a developer to commit at least once before handing it over.

**How do I use mob.sh in my team to work in a micro-commit workflow so far?**
As we mob, we add lots of manual micro-commits that get mixed up with `mob next` commits in our history. When we are finished, we use `mob done --no-squash` which keeps the commit history for us. We then cleanup the history and squash all `mob next` commits, so that we have only our manual commits left when we push. Cleaning up the history is tedious, so we are using a script for it (https://gist.github.com/gregorriegler/5b991f859255549bd15e3d61c3842d57).
The script works as long as there is a final manual commit.
For us this works quite well however, I think more people would benefit from having this feature built into mob.sh.

**But how could we accomplish this?**
I can think of the following options:

A) Add another command `mob newcommand` (need to find a good name) that takes care of squashing `mob done` commits just like our script. It would have to ask the user to enter a message for the final manual commit it would add, in case the current final commit was a `mob next` commit.

Scenario A.1)

1. `mob done --no-squash`
2. `git commit -am "finished"`
3. `mob newcommand`
4. info: "all wip commits have been squashed"

Scenario A.2)

1. `mob done --no-squash`
2. `mob newcommand` (the last commit is a `mob next` commit here)
3. info: "please enter a message for the final commit"
4. user enters: "final commit message"
5. info: "all wip commits have been squashed"

B) Add another option for `done`. E.g. `mob done --new-option` that does just the same thing as `mob done --no-squash && mob newcommand` from A)

C) Change the `--no-squash` option to do what B does, but then the naming is a poor fit.
It would squash wip commits when the name was no-squash.

What do you think?
Which solution would you prefer?
Can you propose an even better way to accomplish this?
What names for commands/options would you suggest?
What Issues do you see that I am missing here?

**Comment by simonharrer** [comment]
According to the design guidelines (see readme), mob should not be interactive and doesn’t do changes in the base branch.

That being said, I’d rather have a separate command that only does what your script does. Something like mob squash-wip-commits. But it operates on the wip branch only and after having done the squashing does a force push. Then you can use mob done —no-squash as usual.

**Comment by gregorriegler** [comment]
Staying non-interactive would only affect the scenario where the last commits were wip commits.
I'm thinking of just squashing those last wip commits, and staging them on the base branch. Just like `mob done` would do.
At the same time I would like to combine all other wip commits with their following manual commits.
The best way would be, if all of this would be done in a single command.

**Scenario: Final commits are wip commits**

1. alice: mob start
2. alice: mob next (wip commit)
3. peter: mob start
4. peter: git commit (manual commit)
5. peter: mob next (wip commit)
6. bob: mob start
7. bob: mob somecommand 
 
Here, somecommand would  combine the commits 2 and 4. Changes of 5 would be staged on the base branch for bob to commit manually.

**Scenario: Final commit was a manual commit**
1. alice: mob start
2. alice: mob next (wip commit)
3. bob: mob start
4. bob: git commit (manual commit)
5. bob: mob somecommand

Here, commits 2 and 4 would be combined. No more changes have to be staged on the base branch. Bob just has to push the commit.


Thinking about this, the finishing should really be done in one command. 
Doing `mob done --no-squash` only to run yet another mob command is just an unnecessary obstacle.
I think either `mob done --no-squash` should handle it all, or another command should handle it all.
But I think if we had this feature in another command than `--no-squash`, `--no-squash` would effectively become obsolete.
You just don't need it anymore, because you would always run this new command.
So it probably makes sense to have `--no-squash` implement this behaviour. But then the name is quite poor.
Should be something like `mob done --unwip` or something instead.

**Comment by simonharrer** [comment]
mob controls the wip branch but should do as little as possible (best would be nothing) to the base branch - the user is responsible for the base branch though. I would expect that mob does the rebase that squashes the wip commits into the superceding manual commits on the wip branch before merging it back into the base branch.

My suggestion was to introduce this wip-to-manual-squashing step on the wip branch as a separate command and when we shipped this we can still think of a way to combine it via a command line option or whether the user combines it.

Here's what I mean:

```bash
# most simplest way
bob $ mob squash-wip-commits
bob $ mob done --no-squash

# user combines the commands
bob $ mob squash-wip-commits && mob done --no-squash # maybe even use an alias for that

# tool combines the commands
bob $ mob done --no-squash --squash-wip-commits # or something like this
```

We can still add or change `mob done` to make it more powerful, but adding the other command would improve the tool as well, because one might only want to squash the wip commits and still keep working on the wip branch.

**Comment by gregorriegler** [comment]
Sounds like a plan to me.
Just what do we do if the last commit was a wip commit before one runs `mob squash-wip-commits`.
We cannot just leave the wip commit as when one runs `mob done --no-squash` afterwards, the wip commit would make it to the base branch.
What if `mob squash-wip-commits` checks that and prints a warning like so: 
"Cannot squash wip commits as the final commit is a wip commit. Please add a final describing manual commit before squashing."

**Comment by simonharrer** [comment]
Maybe let the command fail with an exit code if the last commit is a wip commit.

How do we detect wip commits, though? I assume withe the set wip commit message. What happens when one person in the mob uses another wip commit message?

**Comment by gregorriegler** [comment]
only works if all use the same wip message.
most people will use the default. 
if the user doing the squash uses the default, I'd just squash.
If the user doing the squash uses a custom wip message, I'd print a warning.
Don't know a better way to identify differing wip messages.

**Comment by gregorriegler** [comment]
@simonharrer currently working on it in https://github.com/remotemobprogramming/mob/tree/keep-micro-commits
Please take a look at `TestSquashWipCommits_acceptance` which should test the whole thing.
It calls `squashWipCommits(configuration)` which needs mob.sh installed in the given version which is a chicken and egg problem.
Notice line 12 in squash_wip_commits.go
https://github.com/remotemobprogramming/mob/blob/1a0eb84079762a8ecead556dd26c46fdc02aee16/squash_wip_commits.go#L12

**Comment by simonharrer** [comment]
Some aspects

- the trimSpace change could be another PR
- you could use `go run github.com/remotemobprogramming/mob squash-wip-commits --git-editor` instead calling `mob squash-wip-commits --git-editor` directly in the test. This might solve your chicken-egg-problem. And I wouldn't use a relative path here but an absolute path to the mob executable.
- be sure that you only change the environment variable of GIT_EDITOR temporarily. It should not change that variable permanently for the user.

**Comment by simonharrer** [comment]
Also important to think about error scenarios and how to recover in those cases.

**Comment by gregorriegler** [comment]
> Some aspects
> 
> * the trimSpace change could be another PR

did
> * you could use `go run github.com/remotemobprogramming/mob squash-wip-commits --git-editor` instead calling `mob squash-wip-commits --git-editor` directly in the test. This might solve your chicken-egg-problem. And I wouldn't use a relative path here but an absolute path to the mob executable.

`go run github.com/remotemobprogramming/mob` doesn't work using `go test`
```
ERROR cannot find module providing package github.com/remotemobprogramming/mob: working directory is not part of a module
```
see also github actions:
https://github.com/remotemobprogramming/mob/runs/2248750077?check_suite_focus=true

but it works when I run the tests via IntelliJ using "Test Kind": "Package"
I don't understand.

> * be sure that you only change the environment variable of GIT_EDITOR temporarily. It should not change that variable permanently for the user.

sure

**Comment by gregorriegler** [comment]
Ok, this made it work:
https://github.com/remotemobprogramming/mob/commit/eb65c1d0ebc934684c04203fd99d60840271245e

**Comment by gregorriegler** [comment]
I should add, that i wasn't able to test this new feature on macOS or Windows yet.
