### ISSUE TITLE
mob start with negative number

### ISSUE THREAD

**Issue by jlangr** [remotemobprogramming/mob#154]
A minor issue; if you pass a negative number it immediately issues the "mob next" voice command.

**Comment by simonharrer** [comment]
What would you expect to happen instead?

**Comment by jlangr** [comment]
There are a bunch of options... but it probably should not speak.

The only reason I bring it up is that I've seen a few people do it now, and then I did it myself accidentally.

Some options: Issue an error, pretend it's positive, or assume it's not specified came to mind. It also should not say "-1 minutes timer started...;" maybe say "indefinite timer started" or something like that.

Or you could just ignore the whole thing, it's really not a big deal, just a little awkward. :-)

**Comment by simonharrer** [comment]
I don’t want to invest too much code. What would be okay is to have a max(0,valueFromUser) in there. This should reduce confusion with little code.

**Comment by jlangr** [comment]
Works for me!

**Comment by simonharrer** [comment]
Fixed in next version.
