### ISSUE TITLE
mob does not include unpushed commits in the mob branch

### ISSUE THREAD

**Issue by TrentonAdams** [remotemobprogramming/mob#156]
All of these except `blah` were in my .gitignore.
```
$ git status
A  .idea/limited-wip.xml
A  blah
A  good.sh
A  junit-migrate.sh
A  rmi/apas-dataset-synchronizer.log
A  rmi/apas-dataset-synchronizer.log.debug
A  selenium/acceptance/.env.old
```

All I did was...

```bash
mob start
echo hello > blah
mob done
```

And mob.sh decided it should add files that are explicitly ignored.  That seems non-functional.

**Comment by TrentonAdams** [comment]
Oh, it's worse than that.  I started a mob session without first pushing my changes up, so it appears it did not notice that, and decided to create the branch off the origin branch, which did not include my .gitignore changes. 

I'm going to take a look at the mob.sh code.

**Comment by simonharrer** [comment]
Can you rename this issue, please. It’s somewhat misleading for others because it’s not an issue with git and gitignore files but with unpushed local commits. :-)
