### ISSUE TITLE
Error when using a .gitignore_global file

### ISSUE THREAD

**Issue by JamesArthurHarrison** [remotemobprogramming/mob#174]
Hi,

We are working on Ubuntu 20.04 and are trying to get mob.sh working out our machines. However, it is causing a git permissions error:

```
11:38 $ mob start
 ERROR git status --short
 ERROR warning: unable to access '/home/jamesharrison/.gitignore_global': Permission denied
 ERROR fatal: cannot use /home/jamesharrison/.gitignore_global as an exclude file
 ERROR exit status 128
```

Here are the permissions (etc.) for the .gitignore_global file:

`-rw-r--r--  1 jamesharrison jamesharrison        99 May 28 11:37 .gitignore_global`

All works  when `.gitignore_global` is deleted, although we need `.gitingore_global`. Additionally the `.girignore_global` never usually creates errors.

Neither adding additional permissions (`chmod 777 .gitignore_global`) nor changing the owner (`chown` etc) to root seems to change this issue (though I should have to do neither of those things). This leads me to suspect either I'm missing something, or there could be an issue with mob.sh and `.gitignore_global`.

Advice/help greatly received!
Blessings,
James

**Comment by simonharrer** [comment]
Hm, `mob` basically only executes `git status --short` via the golang standard library `exec.Command`. Nothing fancy happening here as far as I understand it.

A few questions that might help to get to the bottom of this:

1. How did you install the `mob` tool? 
2. Does running `mob status --short` work in your case? 
3. How do you include the global gitignore file? Can you show the portion of your gitconfig that includes this?

**Comment by JamesArthurHarrison** [comment]
Thank you so much! Lets see...

@simonharrer 
1. I installed it via puppet-ubuntu, which in turn installed it as a snap package.
2. `git status --shot` does nothing, `mob status --short` outputs this:

```
> you aren't mob programming
> on base branch branchName (wip branch mob/branchNamel)
👉 to start mob programming, use

mob start
```
...Running `mob start` just gets the previously mentioned error.
3. It's used exactly as a normal `.gitignore` file but it in our home directory - git automatically 'merges' the content of this with the content of every other .gitignore file to allow things to be globally ignored (so as every project needs to ignore the `.vendor` folder we ignore it in `.gitignore_global` rather than repeat it in every repo's `.gitignore` file. The config section you asked for is this:
```
[core]
    excludesfile = /home/jamesharrison/.gitignore_global
```

@nikolashermann 
Yes, this sounds like this is the root (or home ;-) ) of the problem!  Thanks so much for spotting it... I now realise those answers are not really needed! Thanks for getting that ready to merge - I guess we just wait on the review team looking and approving the MR. 

Thank you both! Blessings :-)

**Comment by simonharrer** [comment]
In the meantime you can install it via the default curl to sh command from mob.sh - this should work.

**Comment by nikolashermann** [comment]
@JamesArthurHarrison The review got approved by the snapcraft team, you can now use `~/.gitignore` or `~/.gitignore_global` as global excludeFile
