### ISSUE TITLE
Create remote branch if it doesn't exist

### ISSUE THREAD

**Issue by michelgrootjans** [remotemobprogramming/mob#175]
When starting on a new branch, our current flow is:
```
git checkout -b my-branch
git push origin my-branch -u
mob start
```

Would it make sense to enable this flow:
```
git checkout -b my-branch
mob start [--push-remote|-r]
```

or even better:
`mob start [--push-remote|-r] my-branch`

**Comment by simonharrer** [comment]
Thanks for your suggestion.

We could start with the second option to allow mob start to create the remote branch if the base branch doesn't exist yet. I would propose to rename the variable differently like so:

```
git checkout -b my-branch
mob start [--push-base-branch-remote|-p]
```

could be a solution. What git command should the push be?

**Comment by michelgrootjans** [comment]
Are there any details of the current mob flow that have an effect on this decision? If we would start with `git push origin my-branch -u`, does that affect any other behavior of mob? Is that consistent with the previous behavior?

**Comment by simonharrer** [comment]
See design concepts at https://github.com/remotemobprogramming/mob#design-concepts:

- mob owns its wip branches. It will create wip branches, make commits, push them, but also delete them.
- mob requires the user to do changes in non-wip branches.

This feature would go against this principle because `mob` would manage non-wip branches. It's okay in this case because we only push something, and this change is very limited and doesn't destroy anything.

That being said, I thing using `-u` in the push might do it, but I haven't verified anything.

**Comment by michelgrootjans** [comment]
I think it's better to keep to these design guidelines. I could just as well create a bash script or an alias that solves my specific problem.

**Comment by simonharrer** [comment]
A solution would be to put such a bash script in the README as a helper for others who work with feature branches a lot?

**Comment by michelgrootjans** [comment]
The thing I would like to achieve is [rendered here](https://www.plantuml.com/plantuml/proxy?cache=no&src=https://gist.githubusercontent.com/michelgrootjans/3b76f6ed1e597f88e7604cbdb43b1402/raw/73d87259a23ff9d5fb9ef397b8b34b74ae79d090/test.puml).

As I reread the README, I realise this customisation doesn't quite fit with the simplicity of the tool. I'll happily share the script I come up with once I get to it.

**Comment by simonharrer** [comment]
Would love a PR from you with such a script. And depending on the demand, we might add it at some point directly within `mob`.

**Comment by michelgrootjans** [comment]
I finally settled on a very simple function in my `.zprofile`:
```
mob-start() { git checkout -b "$@" && git push origin "$@" -u && mob start -i; }
```

This does exactly what I need.

**Comment by simonharrer** [comment]
Awesome. I've put this in the README. See https://github.com/remotemobprogramming/mob/commit/0b6aa26e399a9ed585da70c1cb9fbca7520effd0
