### ISSUE TITLE
eSpeak setup doesn't work with WSL2

### ISSUE THREAD

**Issue by rdmueller** [remotemobprogramming/mob#176]
it seems that there is no easy access for eSpeak to the sound card in WSL2 on windows.

Workaround is to install eSpeak on windows und use espeak.exe from WSL2

**Comment by rdmueller** [comment]
created a PR to add some additonal help for this issue to the README.md

**Comment by simonharrer** [comment]
No sound support on wsl2 is bad. How did you install it? Perhaps adding a hint in the install bash script about espeak on wsl2 might help users as well?

**Comment by rdmueller** [comment]
the trick is that you can execute windows CLI tools from WSL. So you just install espeak on WSL and reference it from the `say` script.
The install bash script already redirects the user to the `README.md` section where I hopefully explained it in such a way that WSL users know what to do :-) (see PR). I guess this will be enough.

btw: cool idea to use espeak :-)
