### ISSUE TITLE
Handling of multiple wip branches per repository

### ISSUE THREAD

**Issue by gregorriegler** [remotemobprogramming/mob#178]
I was recently running a coding dojo where we tried to have two mobs work on the same kata in the same repository and use mob.sh. They were all new to the tool (I introduced them).

For the mob that started first, everything went smoothly.
For the mob that started second, they got the warning "qualified mob branches detected".
This threw them off the rails. 
First, they tried to set the branch manually with the --branch option and I think they made a typo or something.
They could not manage to fix it, so they just stopped using the tool to make progress.
I understand the purpose of the "check for WIP branches" feature but in this case, it created more harm than good.

Now trying to think of a better way to handle this despite staying non-interactive.

Perhaps having mob start just do what it does when there was only a single wip branch,
but then showing a warning: There is another mob session going on at that branch ... type `mob join` to join it instead

**Comment by gregorriegler** [comment]
Another idea would be to keep it as is, but only show the "qualified mob branches detected" as long as no matching wip branch currently exists. So, effectively only the first driver would get the warning and deals with it.
But dealing with it should be easier. Like `mob start force`.
All following drivers don't see the warning anymore, as the tool then recognizes that the WIP branch exists.

**Comment by simonharrer** [comment]
I see. That's a scenario I haven't considered yet. Will have to think about it. Will respond when I had time to process.

**Comment by simonharrer** [comment]
Shifting the error down to a nicely worded warning should suffice. A configuration for the hold behavior is thinkable, but I'm not sure whether we need that. If you like, you can open a PR for changing the error to a warning along with tests.

**Comment by simonharrer** [comment]
Having a way to check the available mob sessions going on would also be interesting. Maybe ‚mob branch‘ could display all remote mob branches available.

**Comment by gregorriegler** [comment]
I see a lot of functions dealing with branches as a primitive String, and already found duplication there.
I think everything would be easier if we extracted a branch module that contained all the functions.
something like 
```
type Branch
type WipBranch
func determineWipBranch(Branch, Configuration) WipBranch
```
not sure yet how this would look like in go

**Comment by simonharrer** [comment]
Introducing a type branch (and other types) which is a string would probably suffice already. I don’t want to introduce modules just jet.

**Comment by simonharrer** [comment]
I think we addressed the main thing in this issue. I'm thinking about closing it. Any objections @gregorriegler ?

**Comment by gregorriegler** [comment]
No, closing it.
