### ISSUE TITLE
Handling ssh based git interactions when passphrase is involved

### ISSUE THREAD

**Issue by harshild** [remotemobprogramming/mob#184]
When Git is configured using RSA keys that have a passphrase attached to them, git mob and other commands run into error as there is no prompt to enter a passphrase.

**Comment by simonharrer** [comment]
Hm, strange.

On windows, a popup typically opens up where to enter the passphrase.

I know that one user on macOS use `ssh-add` to not have to enter the passphrase for a while. You could try to use this.

**Comment by simonharrer** [comment]
@harshild did the workaround solve your problem?

**Comment by harshild** [comment]
Sorry for the late response. 

Based on your response, figured this was an issue as the ssh key was not added to ssh-agent. As soon as it was added it started working.

This was a false alarm and it's safe to close the issue
