### ISSUE TITLE
`mob start` on new branch should create remote branch

### ISSUE THREAD

**Issue by lamalex** [remotemobprogramming/mob#185]
I’ve noticed a pattern of usage when using mob- 
```
$ git checkout -b <new-branch-name>
$ mob start 25
… mob error tells me to push to a remote branch …
$ git push <remote> <new-branch-name> —set-upstream
$ mob start 25
```

Seems that mob could just push to remote and then initiate the mob session. Is there a good reason it doesn’t before I work on a PR?

**Comment by lamalex** [comment]
I just noticed the README change including a small shell function to combine the commands, but I wonder if that doesn’t indicate a workaround for a pain point in the tool’s UI.

**Comment by simonharrer** [comment]
Reason lies within https://mob.sh/#design-concepts especially those two:

- mob owns its wip branches. It will create wip branches, make commits, push them, but also delete them.
- mob requires the user to do changes in non-wip branches.

I don't want to deviate from them just yet.

**Comment by simonharrer** [comment]
I'm closing this now, but feel free to reopen if you want to continue the discussion.
