### ISSUE TITLE
mob start -i when remote branch is missing

### ISSUE THREAD

**Issue by jlangr** [remotemobprogramming/mob#190]
hi Simon--

I'm on 1.8, so I think I have the latest version.

A **common** quandary I've seen folks get into:

- create new feature branch XYZ
- do some new work
- oops, forgot to do a `mob start` before doing the new work
- do a `mob start -i` to include the unstaged new work
- oops, forgot to push the feature branch to origin

```
 ~/devel/ford/ttt-aem-components> mob start -i                                                                                                                                               (jeff_new_feature_demo) ✗ 
   git stash push --include-untracked --message mob-stash-name
   git fetch origin --prune
 ERROR Remote branch origin/jeff_new_feature_demo is missing
 👉 To set the upstream branch, use

   git push origin jeff_new_feature_demo --set-upstream
   ```
   
So, the stash gets pushed but not popped. The developers panic, particularly the ones who are kind of missing the point about doing small increments of work, and who wait for an hour or two before doing a `mob next`.

A `git stash pop` does the trick, but it's a little panicky at first for folks not paying enough attention.

Is there a good fix for this? Perhaps check for the remote branch first and abort before stashing if it doesn't exist?

BTW: I started looking through the reflog for their commits, because it wasn't clear how many times they'd done a `mob next` until I looked at their bash command history (and then the problem was obvious). In any case: It would also be nice if, when you do a `mob next`, it displays the SHA of the commit created.

thanks!

**Comment by simonharrer** [comment]
> BTW: I started looking through the reflog for their commits, because it wasn't clear how many times they'd done a mob next until I looked at their bash command history (and then the problem was obvious). In any case: It would also be nice if, when you do a mob next, it displays the SHA of the commit created.

I've added this in 53c06c2 but not sure on how the best format would be. I also moved showing the changes right below making the commit where they belong.

> Is there a good fix for this? Perhaps check for the remote branch first and abort before stashing if it doesn't exist?

Great catch as well. I reorderd the code such that all errors preventing `mob start` from failing are checked BEFORE any `git stash`. This includes also the issue you mentioned, but some others as well. So I think this might really improve the usability of the tool. Thanks for pointing this out!
