### ISSUE TITLE
Bug: Delayed mob start loses local changes

### ISSUE THREAD

**Issue by christianhujer** [remotemobprogramming/mob#193]
When running `mob start` too late, a user might lose their changes.

Steps to reproduce:
1. Create a new repository on GitHub, with a `README.md`.
2. Clone that repository.
3. In the clone, execute:
```
$ mkdir true
$ cd true
$ echo true >>.gitignore
$ echo 'int main(void) { return 0; }' >true.c
$ make true
cc     true.c   -o true
$ rm true
$ mob start
 > cannot start; clean working tree required
 > untracked files present:
 > .gitignore
 > true.c
 👉 To start, including uncommitted changes, use

   mob start --include-uncommitted-changes

$ mob start --include-uncommitted-changes
   git stash push --include-untracked --message mob-stash-name
 ERROR mob expects the current working directory to be a git repository.
$ pwd
/home/christian.hujer/git/nelkinda/mob-example/true
$ cd ..
$ ls
README.md
$ git branch -a
* trunk
  remotes/origin/HEAD -> origin/trunk
  remotes/origin/trunk
```

**Expected behavior:**
The directory `true` still exists and is now, along with its contents `.gitignore` and `true.c` under version control, committed, and pushed to the branch `remotes/origin/mob/trunk`.

**Actual behavior:**
The directory `true` mysteriously disappeared, along with all of its contents.

The deletion happens at this step:
```
$ mob start --include-uncommitted-changes
```
when performing
```
   git stash push --include-untracked --message mob-stash-name
```

The deletion probably happens because the current working directory does not include at least one file that already is under version control.

To fix this, the implementation of `mob start --include-uncommitted-changes` could
1. Remember the current working directory `savedwd="$(pwd)"`
2. Change to the base directory of the working tree `cd "$(git rev-parse --show-toplevel)"`
3. Run the `git stash push --include-untracked --message mob-stash-name`
4. Recreate the saved working directory `mkdir -p "$(savedwd)"`
5. Change back to the saved working directory `cd "$(savedwd)"`
Other ways of fixing this might be possible, I haven't explored that.

**Comment by christianhujer** [comment]
Ah yes, it's in the stash, indeed. A message that this is in the stash would be helpful. That too would work.
Whatever works and is easy to implement.

**Comment by simonharrer** [comment]
Good point about adding a message to state how to recover in case of an error. Might be the simplest solution, especially because this bug shouldn’t happen too often.

**Comment by simonharrer** [comment]
Added an info on how to recover: https://github.com/remotemobprogramming/mob/commit/f623760ed747bab75c467a4e6a847a03377879d2

**Comment by simonharrer** [comment]
Okay, I think I solved it. `git ls-tree -r HEAD --full-name --name-only  .` returns an empty string when the current directory is not part of the current HEAD commit. With this, we can determine whether a `git stash` would stash away our current directory or not. In this case, we fail with an error message. This will be part of the v1.12.0 release.

**Comment by simonharrer** [comment]
See https://github.com/remotemobprogramming/mob/releases/tag/v1.12.0 :-)
