### ISSUE TITLE
mob --version fails if not run in a git repository

### ISSUE THREAD

**Issue by draptik** [remotemobprogramming/mob#194]
Since v1.11 `mob --version` fails if not run in a git repository. And in turn it doesn't return the version number.

Not sure if this is the expected behavior?

**Comment by simonharrer** [comment]
Not expected. That’s a bug.

**Comment by simonharrer** [comment]
Fixed in https://github.com/remotemobprogramming/mob/commit/34a0dd0c8453985919a563e899e0fea655530614
