### ISSUE TITLE
Feature Request: Limit the branches we fetch from the remote

### ISSUE THREAD

**Issue by seanpoulter** [remotemobprogramming/mob#199]
Hi folks,

I've recently started using `mob` and discovered `mob start` will fetch the branches from the repo. The repo I'm working on has over 1,000 branches so `git fetch` takes a while and leaves me with a lot of unwanted remote branches. Would you welcome a PR to narrow down the branches we fetch?

It is possible to filter down the branches we fetch using a "refspec" with a wildcard. For example, give me all the `mob/*` branches from `origin`:

```
git fetch origin refs/heads/mob/*:refs/remotes/origin/mob/*
#         ^^^^^^            ^^^                ^^^^^^ ^^^
```

Would you prefer the change to be enabled using configuration like `MOB_ONLY_FETCH_WIP`, or by default?

Thanks!

**Comment by seanpoulter** [comment]
Before I make the change I'd like to make the change easy. Is it safe to have all the CLI commands make the same call to `git fetch`? Here's a diagram of how things look now with the calls I want to change with a 🚩.

![image](https://user-images.githubusercontent.com/2585460/140632235-d2c75860-9d49-4c89-b9ce-f548619f0bc4.png)

I'd like to replace the calls to `git("fetch", ...)` with calls to `fetch(configuration)`:

![image](https://user-images.githubusercontent.com/2585460/140632097-15c9817b-1645-46b1-b774-e7753da024bf.png)

Sound good? The tests still pass.

**Comment by simonharrer** [comment]
Should be fine.

**Comment by seanpoulter** [comment]
Thanks Simon. I'll make that change.

I'd propose that we always fetch:
- The base branch - either `master` or removing the prefix, separator, and suffix.
- `mob-session`
- The wildcard for the WIP branches like `<prefix><**any** branch><separator><qualifier>`

This _should_ work for all cases. Let me know if you see that I'm missing something. There are two edge cases I can think of:
- If we could set the prefix to an empty string the pattern might match everything. We can't use an empty prefix though.
- If we checkout a commit that isn't a named branch, we might have a hard to finding the base branch name. This is also not a problem because `mob start` fails from a detached HEAD.
  ```
  ERROR fatal: ambiguous argument 'refs/heads/HEAD...refs/remotes/origin/HEAD': unknown revision or path not in the working tree.
  ERROR Use '--' to separate paths from revisions, like this:
  ```

Here's a flowchart I used to reason about it:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgaXNfZGV0YWNoZWRfaGVhZHtJcyBkZXRhdGNoZWQgSEVBRD99IC0tPiB8WWVzfCBfKE5vdCBwb3NzaWJsZSlcbiAgaXNfZGV0YWNoZWRfaGVhZFxuICAgIC0tPiB8Tm98IGlzX2xlZ2FjeXtJcyBsZWdhY3k_fVxuICAgIC0tLS0-IHxZZXN8IGxlZ2FjeShtYXN0ZXIgbW9iLXNlc3Npb24pXG5cbiAgaXNfbGVnYWN5XG4gICAgLS0-IHxOb3wgaXNfZGVmYXVsdF9wcmVmaXh7SXMgZGVmYXVsdDxicj5NT0JfV0lQX0JSQU5DSF9QUkVGSVg_fVxuICAgIC0tPiB8WWVzfCBpc19kZWZhdWx0X3F1YWxpZmllcntJcyBkZWZhdWx0PGJyPk1PQl9XSVBfQlJBTkNIX1FVQUxJRklFUj99XG4gICAgLS0-IHxZZXN8IGRlZmF1bHRfKDxicmFuY2g-LCBtb2IvPGJyYW5jaD4pXG5cbiAgaXNfZGVmYXVsdF9xdWFsaWZpZXIgLS0-IHxOb3wgcXVhbGlmaWVyX2NvbmZpZ3VyZWQoPGJyYW5jaD4sIG1vYi88YnJhbmNoPjxzZXBhcmF0b3I-PHF1YWxpZmllcj4pXG5cbiAgc3ViZ3JhcGggTGVnYWN5XG4gICAgbGVnYWN5XG4gIGVuZFxuXG4gIHN1YmdyYXBoIFF1YWxpZmllciBDb25maWd1cmVkXG4gICAgcXVhbGlmaWVyX2NvbmZpZ3VyZWRcbiAgZW5kXG4gIHN1YmdyYXBoIFByZWZpeCBhbmQgUXVhbGlmaWVyIENvbmZpZ3VyZWRcbiAgICBwcmVmaXhfYW5kX3F1YWxpZmllcl9jb25maWd1cmVkXG4gIGVuZFxuICBzdWJncmFwaCBQcmVmaXggQ29uZmlndXJlZFxuICAgIHByZWZpeF9jb25maWd1cmVkXG4gIGVuZFxuICBzdWJncmFwaCBEZWZhdWx0IENvbmZpZ3VyYXRpb25cbiAgICBkZWZhdWx0X1xuICBlbmRcblxuICBpc19kZWZhdWx0X3ByZWZpeFxuICAgIC0tPiB8Tm98IHByZWZpeF9jb25maWd1cmVkX2lzX2RlZmF1bHRfcXVhbGlmaWVye0lzIGRlZmF1bHQ8YnI-TU9CX1dJUF9CUkFOQ0hfUVVBTElGSUVSP31cbiAgICAtLT4gfFllc3wgcHJlZml4X2NvbmZpZ3VyZWQoPGJyYW5jaD4sIDxwcmVmaXg-PGJyYW5jaD4pXG5cbiAgcHJlZml4X2NvbmZpZ3VyZWRfaXNfZGVmYXVsdF9xdWFsaWZpZXIgLS0-IHxOb3wgcHJlZml4X2FuZF9xdWFsaWZpZXJfY29uZmlndXJlZCg8YnJhbmNoPiwgPHByZWZpeD48YnJhbmNoPjxzZXBhcmF0b3I-PHF1YWxpZmllcj4pXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoibmV1dHJhbCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)](https://mermaid.live/edit/#eyJjb2RlIjoiZ3JhcGggVERcbiAgaXNfZGV0YWNoZWRfaGVhZHtJcyBkZXRhdGNoZWQgSEVBRD99IC0tPiB8WWVzfCBfKE5vdCBwb3NzaWJsZSlcbiAgaXNfZGV0YWNoZWRfaGVhZFxuICAgIC0tPiB8Tm98IGlzX2xlZ2FjeXtJcyBsZWdhY3k_fVxuICAgIC0tLS0-IHxZZXN8IGxlZ2FjeShtYXN0ZXIgbW9iLXNlc3Npb24pXG5cbiAgaXNfbGVnYWN5XG4gICAgLS0-IHxOb3wgaXNfZGVmYXVsdF9wcmVmaXh7SXMgZGVmYXVsdDxicj5NT0JfV0lQX0JSQU5DSF9QUkVGSVg_fVxuICAgIC0tPiB8WWVzfCBpc19kZWZhdWx0X3F1YWxpZmllcntJcyBkZWZhdWx0PGJyPk1PQl9XSVBfQlJBTkNIX1FVQUxJRklFUj99XG4gICAgLS0-IHxZZXN8IGRlZmF1bHRfKDxicmFuY2g-LCBtb2IvPGJyYW5jaD4pXG5cbiAgaXNfZGVmYXVsdF9xdWFsaWZpZXIgLS0-IHxOb3wgcXVhbGlmaWVyX2NvbmZpZ3VyZWQoPGJyYW5jaD4sIG1vYi88YnJhbmNoPjxzZXBhcmF0b3I-PHF1YWxpZmllcj4pXG5cbiAgc3ViZ3JhcGggTGVnYWN5XG4gICAgbGVnYWN5XG4gIGVuZFxuXG4gIHN1YmdyYXBoIFF1YWxpZmllciBDb25maWd1cmVkXG4gICAgcXVhbGlmaWVyX2NvbmZpZ3VyZWRcbiAgZW5kXG4gIHN1YmdyYXBoIFByZWZpeCBhbmQgUXVhbGlmaWVyIENvbmZpZ3VyZWRcbiAgICBwcmVmaXhfYW5kX3F1YWxpZmllcl9jb25maWd1cmVkXG4gIGVuZFxuICBzdWJncmFwaCBQcmVmaXggQ29uZmlndXJlZFxuICAgIHByZWZpeF9jb25maWd1cmVkXG4gIGVuZFxuICBzdWJncmFwaCBEZWZhdWx0IENvbmZpZ3VyYXRpb25cbiAgICBkZWZhdWx0X1xuICBlbmRcblxuICBpc19kZWZhdWx0X3ByZWZpeFxuICAgIC0tPiB8Tm98IHByZWZpeF9jb25maWd1cmVkX2lzX2RlZmF1bHRfcXVhbGlmaWVye0lzIGRlZmF1bHQ8YnI-TU9CX1dJUF9CUkFOQ0hfUVVBTElGSUVSP31cbiAgICAtLT4gfFllc3wgcHJlZml4X2NvbmZpZ3VyZWQoPGJyYW5jaD4sIDxwcmVmaXg-PGJyYW5jaD4pXG5cbiAgcHJlZml4X2NvbmZpZ3VyZWRfaXNfZGVmYXVsdF9xdWFsaWZpZXIgLS0-IHxOb3wgcHJlZml4X2FuZF9xdWFsaWZpZXJfY29uZmlndXJlZCg8YnJhbmNoPiwgPHByZWZpeD48YnJhbmNoPjxzZXBhcmF0b3I-PHF1YWxpZmllcj4pXG4iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwibmV1dHJhbFwiXG59XG4iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

**Comment by seanpoulter** [comment]
Hrm ... when the remote branches do not exist, `git fetch` throws and does not get the remaining refs. It seems to be running with `--atomic` by default. 🤔 

```
$ git fetch --prune origin master mob-session refs/heads/mob/*:refs/heads/mob/*
fatal: couldn't find remote ref master
```

As a consequence my proposal won't work. I'd have to check if remote has the named branches before we can fetch them which effectively doubles the time. Working with GitHub and my fork, that goes from .7s to 1.5s for two calls:

```
$ git ls-remote --heads origin master mob-session
5a139db2021c6f348fa75fcb4e00972dd2093556        refs/heads/master
#                                                          ^
#                                                          The remote exists. It is safe to fetch.

$ git fetch --prune origin master refs/heads/mob/*:refs/heads/mob/*
#                                ^ 
#                                mob-session is excluded
```

**Comment by simonharrer** [comment]
Is this only an issue with the legacy master/mob-session branches, or for any mob/* branch in general?

**Comment by seanpoulter** [comment]
You've got the right idea Simon. This is only an issue when we specify a specific branch. It affects the legacy branches, but also the other half of the base/WIP branch. It is not a problem when we fetch `refs/heads/mob/*:refs/heads/mob/*` or `HEAD`.

So, for example, if we are collaborating and on `mob/main` I think we will want to fetch the base branch `main` as well.

**Comment by seanpoulter** [comment]
Hi Simon. I no longer need this feature. I propose that we close the issue until someone else would find it useful.

To address the performance issue, I can follow up with the Git community to see if I've overlooked something and I'll update the Issue.

**Comment by simonharrer** [comment]
Fine for me.
