### ISSUE TITLE
Suggestion: Can we update the "How to contribute" docs?

### ISSUE THREAD

**Issue by seanpoulter** [remotemobprogramming/mob#204]
When I follow the [How to contribute](https://github.com/remotemobprogramming/mob#how-to-contribute) section of the README, I see an error when I run `./create-testbed`:

```
$ ./create-testbed    # creates test assets

Creating temporary test assets in 
mkdir: : No such file or directory
```

This seems expected. We provide a directory when we run `create-testbed` from [`mob_test.go:1011`](https://github.com/remotemobprogramming/mob/blob/7274acf151550146f69bca7fe79d52b1ca04b872/mob_test.go#L1011):

```go
	run(t, "./create-testbed", tempDir)
```

I'd suggest we either:

- Remove the line from the docs because it is already run in `mob_test.go`
- Add a note that it is called in `mob_test.go` but it might help during development like: 
  ```shell
  # If you would like to create test fixtures outside of mob_test.go
  # run `create-testbed` with a directory:
  ./create-testbed <directory>
  ```

**Comment by simonharrer** [comment]
First option is probably better as it’s just a test detail.
