### ISSUE TITLE
Suggestion: Migrate the Go GitHub Action

### ISSUE THREAD

**Issue by seanpoulter** [remotemobprogramming/mob#205]
The `cedrickring/golang-action` GitHub Action has been deprecated and will not be maintained to support new versions of Go beyond v1.16. From [the project README](https://github.com/cedrickring/golang-action#readme):

> **IMPORTANT**: This action will **no longer be maintained** by myself and thus will not support versions newer than Golang 1.16. I highly recommend using the [offical actions/setup-go action](https://github.com/actions/setup-go) which does exactly the same as this action (+ with some more features).

I'd suggest and am happy to open a PR to switch us over to the official action.

**Comment by simonharrer** [comment]
Go for it! :-)
