### ISSUE TITLE
Load some config parameters from local file

### ISSUE THREAD

**Issue by koeberlue** [remotemobprogramming/mob#214]
I am currently using `mob` in multiple projects for different teams/customers. For each team we agreed on a separate  `timer name` and one customer requires a special `wip commit message` and `wip branch qualifier`. 

It would be great if the config for these variables could be loaded from a config file that I can put into the repository so I don't have to remember to overwrite my config whenever I switch to another team.

Maybe `mob` could try to look for a file called `.mob` in the root directory of the current repository. If the file is present, the current configuration would be overwrittent with the file content.

### Example

Imagine the environment variables configured like this:

```
MOB_CLI_NAME=mob
MOB_REMOTE_NAME=origin
MOB_WIP_COMMIT_MESSAGE=mob next [ci-skip] [ci skip] [skip ci]
MOB_REQUIRE_COMMIT_MESSAGE=false
MOB_VOICE_COMMAND=say "%s"
MOB_VOICE_MESSAGE=mob next
MOB_NOTIFY_COMMAND=/usr/bin/osascript -e 'display notification "%s"'
MOB_NOTIFY_MESSAGE=mob next
MOB_NEXT_STAY=true
MOB_START_INCLUDE_UNCOMMITTED_CHANGES=false
MOB_WIP_BRANCH_QUALIFIER=
MOB_WIP_BRANCH_QUALIFIER_SEPARATOR=-
MOB_DONE_SQUASH=true
MOB_TIMER=
MOB_TIMER_ROOM=
MOB_TIMER_USER=
MOB_STASH_NAME=mob-stash-name
```

Then assume there was a file called `.mob` at `<root-repository-folder>` with this content:

```
MOB_TIMER_ROOM="amber-room"
MOB_WIP_COMMIT_MESSAGE="[no-build] mob next"
```

When you then call `mob config` within the repository, it should be composed like this:

```
MOB_CLI_NAME=mob
MOB_REMOTE_NAME=origin
MOB_WIP_COMMIT_MESSAGE="[no-build] mob next"
MOB_REQUIRE_COMMIT_MESSAGE=false
MOB_VOICE_COMMAND=say "%s"
MOB_VOICE_MESSAGE=mob next
MOB_NOTIFY_COMMAND=/usr/bin/osascript -e 'display notification "%s"'
MOB_NOTIFY_MESSAGE=mob next
MOB_NEXT_STAY=true
MOB_START_INCLUDE_UNCOMMITTED_CHANGES=false
MOB_WIP_BRANCH_QUALIFIER=
MOB_WIP_BRANCH_QUALIFIER_SEPARATOR=-
MOB_DONE_SQUASH=true
MOB_TIMER=
MOB_TIMER_ROOM="amber-room"
MOB_TIMER_USER=
MOB_STASH_NAME=mob-stash-name
```

**Comment by seanpoulter** [comment]
This would be very useful for my teams as well although in our use case I wouldn't commit the file, and I'd want to specify the path using `--config <path>`. I think this could be pretty quick to implement using https://github.com/joho/godotenv.

**Comment by gregorriegler** [comment]
Great Idea! I also think this would be very useful. My first intuition tells me we should commit the file. But when I walk over the settings, I see that some are "shared" and others are meant for the individual user. Doesn't make sense to commit the individual user settings.

**These settings are bound to the individual user, so it only makes sense in exceptional cases to commit them:**

- MOB_CLI_NAME=mob
- MOB_REMOTE_NAME=origin
- MOB_VOICE_COMMAND=say "%s"
- MOB_VOICE_MESSAGE=mob next
- MOB_NOTIFY_COMMAND=/usr/bin/osascript -e 'display notification "%s"'
- MOB_NOTIFY_MESSAGE=mob next
- MOB_NEXT_STAY=true
- MOB_START_INCLUDE_UNCOMMITTED_CHANGES=false
- MOB_TIMER_USER=
- MOB_STASH_NAME=mob-stash-name

**And Those settings are shared, thus make sense to commit:**

- MOB_WIP_COMMIT_MESSAGE="[no-build] mob next"
- MOB_REQUIRE_COMMIT_MESSAGE=false
- MOB_WIP_BRANCH_QUALIFIER=
- MOB_WIP_BRANCH_QUALIFIER_SEPARATOR=-
- MOB_DONE_SQUASH=true
- MOB_TIMER=
- MOB_TIMER_ROOM="amber-room"

Perhaps we should split those settings in two categories: "project/repository settings" and "user settings", and each category gets its own file?

Another solution I can think of  would be to allow the settings to overwrite themselves. This would avoid the need to separate the settings in categories.

E.g.:
A user has the file `~/.mob` in their home directory, and they may put any settings in there.
The user works on a project which contains another `.mob` file that is checked into the repository.
The Projects `.mob` file only contains "project/repository settings", therefor it does not overwrite the "user settings" in `~/.mob`.

**Comment by koeberlue** [comment]
@gregorriegler Wonderful suggestion. This sounds really intuitive to me.

**Comment by simonharrer** [comment]
In general, I agree. But some settings are hard to put into a box.

For instance,

```
MOB_TIMER_ROOM="amber-room"
```

may be different when multiple teams, mobs, pairs work on the git repository at the same time.

We really need to be careful here.

We should also consider using git config, which already provides a way of adding configuration on a per-repository basis that is not checked in.

**Comment by simonharrer** [comment]
see https://github.com/remotemobprogramming/mob/commit/75a2f28b07b883e5ecb0172b78bd6f033961df66

**Comment by simonharrer** [comment]
Implemented in https://github.com/remotemobprogramming/mob/releases/tag/v2.4.0 :-)
