### ISSUE TITLE
Git's credential.helper config not used

### ISSUE THREAD

**Issue by mederel** [remotemobprogramming/mob#223]
I am using credential.helper = store and am saving my HTTPS credentials in a file in my home folder. I know the security of it all is debatable, but git is still proposing this solution as described in this page: https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage

The issue is that mob does not seem to respect my choices. It is odd as looking as the source code, git command line is called directly.

**Comment by seanpoulter** [comment]
Hi Emile! Thanks for sharing your feedback. Would you like to try to fix it?

I'd like to start by writing a failing test. What do we need to do to have the same problem as you with credential.helper? Vous pouvez répondre en français aussi.

**Comment by simonharrer** [comment]
How did you install the mob tool? Dir sou perhaps install it via snap? Because snap has quite some restrictions limiting some abilities of git…

**Comment by mederel** [comment]
@simonharrer indeed. In between I installed it through the curl script and it is working. Would it not be better to remove the snap installation option altogether if it is that incompatible?

I am closing the issue anyway. Thanks for your reactivity of you both.
