### ISSUE TITLE
Nix expressions is unmaintained and should be dropped

### ISSUE THREAD

**Issue by mweinelt** [remotemobprogramming/mob#226]
Nixpkgs has a packaged version of mob since December 2020, that is well maintained and it would make more sense to reference that than to keep an outdated nix expression in this repository.

https://github.com/NixOS/nixpkgs/commits/master/pkgs/applications/misc/mob/default.nix

cc @jeeger

**Comment by mweinelt** [comment]
I'd kindly ask our package maintainer to look into the matter: @ericdallo

In the meantime I've ported the espeak-ng integration from this package to ours.

**Comment by jeeger** [comment]
Fine by me! I didn't have a lot of time to keep the nix expression up to date, and didn't realize there was one available in nixpkgs.

**Comment by simonharrer** [comment]
Any way I can help to put the right info on the README?

**Comment by mweinelt** [comment]
Declarative Installation goes like so:

```
{ pkgs, ... }:
{
  # for all users
  environment.systemPackages = with pkgs; [ mob ];

  # for an explicit user
  users.users."youruser".packages = with pkgs; [ mob ];
}
```

I won't recommend using `nix-env`.

**Comment by simonharrer** [comment]
Added this info to the README. Please correct me if I got something wrong in the README.

**Comment by mweinelt** [comment]
Perfect!

**Comment by simonharrer** [comment]
Great. Thanks again for you help!
