### ISSUE TITLE
How to get mob.sh to work with password protected SSH keys?

### ISSUE THREAD

**Issue by groma84** [remotemobprogramming/mob#232]
We tried using mob.sh recently in a new group of people.
Everything worked fine until one of us had a password protected SSH key (in Windows 10, if that matters).

Then mob.sh just failed with:
```bash
PS C:\projects\mob-programming> mob start 5
ERROR git fetch origin --prune
ERROR git@our-internal-git-server.de: Permission denied (publickey).
ERROR fatal: Could not read from remote repository.
ERROR
ERROR Please make sure you have the correct access rights
ERROR and the repository exists.
ERROR exit status 128
```

mob.sh never asks for any password, just fails. What's the proper way for us to deal with password protected keys?

**Comment by simonharrer** [comment]
I know for sure that having a password protected ssh file works in macOS.

Can you try out the mob command using the git bash instead of powershell? And can you run the command with —debug and paste the log in here?

**Comment by gregorriegler** [comment]
From a linux perspective, you would need to run a process called ssh-agent which will remember your password. So you're trading a little bit of security for convenience. And then there are several ssh-agent wrappers that attempt to make this all easier. I'm pretty sure there are similar solutions for windows.

**Comment by draptik** [comment]
OT: are there any security benefits using a pw-protected private ssh key when not using advanced features like gpg-signing of git-commits?

**Comment by simonharrer** [comment]
Got it confirmed that it doesn’t work in powershell. Not sure how to overcome this issue. I think the best path forward is to document this and suggest using git bash instead.

**Comment by simonharrer** [comment]
Documentation is in place in the README under "known issues".

**Comment by groma84** [comment]
Thanks for upgrading the documentation so we can avoid this pitfall in the future!
