### ISSUE TITLE
Installation via `go install` installs old version

### ISSUE THREAD

**Issue by ZauberNerd** [remotemobprogramming/mob#233]
Installing `mob` with the `go install` command (https://github.com/remotemobprogramming/mob#using-go-tools) installs an old version (`v1.12.0`).

System information:
```sh
$ uname -a
Linux ubuntu 5.11.0-1025-aws #27~20.04.1-Ubuntu SMP Fri Jan 7 13:09:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.17.6 linux/amd64
$ echo $GOPATH 
/home/ubuntu/.local/share/go
```

I suppose more information can be found here: https://go.dev/blog/publishing-go-modules or here: https://go.dev/blog/v2-go-modules

**Comment by simonharrer** [comment]
Can you install a more recent version when you add the version?

**Comment by ZauberNerd** [comment]
`@main` is the only one that does seems to work:
* `go install github.com/remotemobprogramming/mob@latest` -> `v1.12.0`
* `go install github.com/remotemobprogramming/mob@main` -> `v2.3.0`
* `go install github.com/remotemobprogramming/mob@v2.3.0` -> `go install: github.com/remotemobprogramming/mob@v2.3.0: github.com/remotemobprogramming/mob@v2.3.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

**Comment by simonharrer** [comment]
I see. Looks like that latest is looking for master and not for the main branch.

I currently have no idea how to fix this. If you like, you could have a go at it.

**Comment by ZauberNerd** [comment]
Maybe this is something:
From https://go.dev/blog/using-go-modules
> Each different major version (v1, v2, and so on) of a Go module uses a different module path: starting at v2, the path must end in the major version. In the example, v3 of rsc.io/quote is no longer rsc.io/quote: instead, it is identified by the module path rsc.io/quote/v3. This convention is called [semantic import versioning](https://research.swtch.com/vgo-import), and it gives incompatible packages (those with different major versions) different names.

**Comment by ZauberNerd** [comment]
Here it also says to update the package name: https://go.dev/doc/modules/major-version and here's some information on publishing a go module: https://go.dev/doc/modules/publishing
And here's a more general overview about packages in go: https://go.dev/doc/modules/developing

**Comment by simonharrer** [comment]
I've added the v2 in the module. Let's see whether this solves this issue. Can you double check, please?

**Comment by simonharrer** [comment]
https://github.com/remotemobprogramming/mob/commit/98d020693a600fec8a0b5f2e78a3d0919fd45a06

**Comment by simonharrer** [comment]
ok. this will happen with the next release automatically. let’s wait for that.

**Comment by simonharrer** [comment]
We now have a new release. Any updates regarding issue, now?

**Comment by simonharrer** [comment]
Here's what my console outputs.

```
➜  Projects go install github.com/remotemobprogramming/mob/v2@v2.5.0
go: downloading github.com/remotemobprogramming/mob/v2 v2.5.0
➜  Projects go install github.com/remotemobprogramming/mob/v2@latest
➜  Projects go install github.com/remotemobprogramming/mob/v2@main
go: downloading github.com/remotemobprogramming/mob/v2 v2.5.1-0.20220222204136-41e4ccaa3375
go: downloading github.com/remotemobprogramming/mob v1.12.1-0.20220208122409-fd76871b539c
➜  Projects
```

**Comment by ZauberNerd** [comment]
Yes, thank you. Using the new package name with `/v2` at the end works fine:
* `go install github.com/remotemobprogramming/mob/v2@latest` gives me `v2.5.0`
* `go install github.com/remotemobprogramming/mob/v2@main` gives me `v2.6.0-pre`
* `go install github.com/remotemobprogramming/mob/v2@v2.5.0` gives me `v2.5.0`

**Comment by simonharrer** [comment]
Awesome. Would you mind creating a PR to fix the version examples in the README with your ones in your last comment?

**Comment by ZauberNerd** [comment]
Can do. But what should I do with the go < 1.16 instructions? I don't really know how they would change - can I remove them or should I try to install an older go version and test it to figure out how to write them?

**Comment by simonharrer** [comment]
I think we can remove them.
