### ISSUE TITLE
MOB_WIP_BRANCH_PREFIX from .mob not taken into account

### ISSUE THREAD

**Issue by MrGung** [remotemobprogramming/mob#239]
It seems the prefix is not taken from the values in the` .mob` configuration-file.

I changed other values (`MOB_WIP_BRANCH_QUALIFIER_SEPARATOR`, `MOB_WIP_BRANCH_QUALIFIER`) and `mob config` showed the changes. Changes to `MOB_WIP_BRANCH_PREFIX` were not realised, though.

Using version 2.5.0 of mob (on Windows)

**Comment by hollesse** [comment]
You just found a bug. MOB_WIP_BRANCH_PREFIX is missing in the function parsing the .mob file. Should be a quick fix.

**Comment by hollesse** [comment]
fixed in [e105d46](https://github.com/remotemobprogramming/mob/commit/e105d4605e972f8454c6e7d6b41cb353160d252e)

**Comment by MrGung** [comment]
Is there a schedule for the next release?

**Comment by hollesse** [comment]
Usually there is a new version every four weeks. The last release is about a week old. So the next release is planned in 3 weeks. How important is this bug fix for you?

**Comment by MrGung** [comment]
My colleagues and me have to go back to environment-variables.

I disturbed the mob today by introducing new branches... ;-)


I couldn't find instructions on how to create an EXE myself - I'd try that.

**Comment by simonharrer** [comment]
In this case, as this bug seems critical to you, I can release at the weekend.

**Comment by simonharrer** [comment]
Just curious: would you share your config? Would love to see how you’re using the tool.

**Comment by simonharrer** [comment]
Just released https://github.com/remotemobprogramming/mob/releases/tag/v2.6.0
