### ISSUE TITLE
Installing & running on Windows

### ISSUE THREAD

**Issue by jwedel** [remotemobprogramming/mob#24]
h1. Actual behavior:

After installing go, I ran the installation as documented and got some strange output. The mob executable is there but I am not sure if it is really the expected behavior:

```
C:\Users\****\repos\mob>.\install.cmd
Installing 'mob' ...

SUCCESS: Specified value was saved.
The filename, directory name, or volume label syntax is incorrect.
Directory "" created.
        0 file(s) copied.
'mob.exe' installed to ""
'mob' successfully installed.
Press any key to continue . . .
```

Then I started mob:

```
C:\Users\****\repos\mob>mob
 > you aren't mobbing right now
 ❗ text-to-speech disabled because 'say' not found
```

h1. Expected Behavior
- I was expected the output as documented without the "0 files copied" etc.
- Maybe there should be added a hint that "say" is not available on Windows

h1. Environment
- Windows 10 Enterprise 1809
- go1.14.1 windows/amd64
- Executed on cmd.exe

**Comment by jwedel** [comment]
Ok, I investigated this. It works, when the windows shell is executed with admin privileges. I think the sex command did not behave as expected:

See help: 
```
1) SETX writes variables to the master environment in the registry.

      2) On a local system, variables created or modified by this tool
         will be available in future command windows but not in the
         current CMD.exe command window.
```
So setx acutally worked but the result is not readable in the current shell. So a separate set MOB_HOME should probably do the trick.

**Comment by jwedel** [comment]
Also `set path=` will only work in the current shell.

**Comment by simonharrer** [comment]
Thanks for your contribution. I merged it. As I don't use windows, I trust you on this. :-)

**Comment by jwedel** [comment]
> ` I trust you on this.`

I don't even trust myself :P But I tested it with clean environment.

**Comment by simonharrer** [comment]
@jwedel windows support is now much better. Just execute the install command in git bash `curl -sL install.mob.sh | sh` and it should install smoothly on your system. Would value your feedback.
