### ISSUE TITLE
shasum of release v2.6.0 incorrect

### ISSUE THREAD

**Issue by jomora** [remotemobprogramming/mob#240]
Hi,

I noticed that the `shasum` of the release v2.6.0 does not match the one provided in the respective `.txt` file.
I executed the following commands twice - once on my Mac and in addition in the Azure CloudShell as a sanity check.

```sh
$ curl -sL https://github.com/remotemobprogramming/mob/releases/download/v2.6.0/mob_v2.6.0_darwin_amd64.tar.gz | shasum -a 256
9951d071796dfe5c945254a50f43e7e3634cf011cab63923cc5a5ddd2f3a94f5  -
$ curl -sL https://github.com/remotemobprogramming/mob/releases/download/v2.6.0/mob_v2.6.0_darwin_amd64_checksum.txt
fa759144200ed64951702c323af47ed0
```

Could you please have a look?

Cheers
Jonas

**Comment by simonharrer** [comment]
Thanks for reporting this. 

After some digging, I realized, that we use MD5 checksums. That's why they don't match in your example. 

On my macOS, the following command returns the right checksum.

```bash
$ curl -sL https://github.com/remotemobprogramming/mob/releases/download/v2.6.0/mob_v2.6.0_darwin_amd64.tar.gz | md5
fa759144200ed64951702c323af47ed0
```

**Comment by jomora** [comment]
Thanks for looking into the issue.

I was confused, because I thought that the following lines were related. However, they weren't :)

https://github.com/remotemobprogramming/mob/blob/7f90408b2066838672ab527f85c4ec7bcd5aa1e8/.github/workflows/release.yaml#L43-L46

Actually, the checksum is computed here.

https://github.com/remotemobprogramming/mob/blob/7f90408b2066838672ab527f85c4ec7bcd5aa1e8/.github/build#L14

@simonharrer To avoid confusion in the future, would it make sense to point out that it's a md5 checksum? For example, by adding a hint to either the README or the release notes?

**Comment by simonharrer** [comment]
I think it would more sense to switch to sha hashes altogether. Would you like to contribute that?

**Comment by seanpoulter** [comment]
@simonharrer, correct me if I'm wrong, but we'd need to change the call to `md5sum` in [`.github/build`](https://github.com/remotemobprogramming/mob/blob/main/.github/build#L14)? Would we want to change the filename to make it clear as well? I've noticed the Git releases call it [`sha256sums.asc`](https://mirrors.edge.kernel.org/pub/software/scm/git/).

**Comment by jomora** [comment]
@seanpoulter, the suffix `.asc` is the default file ending for PGP-signed files., so the file you pointed to was _signed_ with PGP.  This means that the whole list of "shasum to filename mappings" that you can see in the file was signed. See also the first line of the file as well as the signature appended at the bottom.

Another point is that the file contains a _mapping_ of shasums to file names for all release artifacts of all versions.
As far as I can see, this approach is not in place for the `mob` tool since there is a single `_checksum.txt` file that contains only the shasum (and not a mapping) per release artifact. In addition, the release artifacts are stored per release and not in a single folder.

However, I think that the file name of the shasum should be changed so that it reflects the used hash algorithm. I would vote for something like:
```
*_sha256_checksum.txt
```

**Comment by simonharrer** [comment]
Adding the hash algo in the checksum file name is a good idea. Let’s go for this!

**Comment by seanpoulter** [comment]
Would you like to try to improve this @jomora? If not, I'll open up a PR this week.

**Comment by jomora** [comment]
@seanpoulter I'll take care presumable today. Thanks for asking.
