### ISSUE TITLE
What to do when someone else executed mob done?

### ISSUE THREAD

**Issue by koeberlue** [remotemobprogramming/mob#246]
Given the use case from the README:

```
# Carola
main $ mob start
mob/main $ echo "hello" > work.txt
mob/main $ mob next

# Maria
main $ mob start
mob/main $ cat work.txt # shows "hello"
mob/main $ echo " world" >> work.txt
mob/main $ mob next

# Carola
mob/main $ mob start
mob/main $ cat work.txt # shows "hello world"
mob/main $ echo "!" >> work.txt
mob/main $ mob done
main $ git commit -m "create greeting file"
main $ git push

# Maria
# ???
```

What command does Maria need to execute now? She is still on the mob branch, but wants to go back to the main branch (and probably remove her local mob branch).

* We usually do a `git switch main`. But this does not feel right and leaves a local mob branch laying around
* `mob reset` looks kind of dangerous since it removes the remote branch. So if there were some communication issues, we might remove a branch that someone might still need

Maybe there could be a  paragraph in the README which explains this. Or should there be a new command?

**Comment by simonharrer** [comment]
Thank you for the question. Greatly exemplified, thanks for that! 

‚mob reset‘ is not for this use case.

Why not just keep on doing ‚mob start‘? Why do you need to go back to main?

Another thing: if feel your urge to remove the local mob branch so to have a clean local repo. But from the point of the mob tool, this is never necessary as mob start will always overwrite the local one, so cleaning it has no value from the tool‘s perspective.

One could think of a command that returns to the base branch and deletes the local mob branch when there is no longer a remote mob branch, or fails if there still is one. 

Another thing: the mob tool originally switched back the base branch after every ‚mob next‘. We worked with this mode for over a year but then switched over to the current system of staying on the mob branch. Perhaps changing the config to always return to the base branch in your team is the solution you are looking for?

**Comment by koeberlue** [comment]
> Why not just keep on doing ‚mob start‘? Why do you need to go back to main?
> 
> Another thing: if feel your urge to remove the local mob branch so to have a clean local repo. But from the point of the mob tool, this is never necessary as mob start will always overwrite the local one, so cleaning it has no value from the tool‘s perspective.

I'm currently working with two customers which both have a requirement of always working on feature branches for various reasons:

* Multiple teams working in the same repository
  * Team constellation changes pretty often. So they agreed on just using the ticket numbers as base branches to not get in the way of each other
* CI/CD pipelines need to run before merging into master
* Software architect (not part of the mob) has to approve the changes (we are trying to get rid of this requirement)

So the obvious way would be to just switch simultaneously to the next feature branch after someone executed `mob done`. I just noticed that most people are confused at this stage. Nothing big, but it would probably make it a little bit easier for newcomers.

> One could think of a command that returns to the base branch and deletes the local mob branch when there is no longer a remote mob branch, or fails if there still is one.

That sounds great. Especially removing the local mob branches would be great. I'm trying to think of a command that would express this behavior but can not come up with something short and comprehensive. Maybe `mob cleanup`?

Maybe it would actually be enough to just add simple explanation to the example in the README to get rid of the confusion.

> Perhaps changing the config to always return to the base branch in your team is the solution you are looking for?

That would probably not solve my problem, as described above.

**Comment by simonharrer** [comment]
There are two concerns: removing the stale mob branches and being on a stale mob branch after someone else did a mob done.

Being on a stale branch can be mitigated with MOB_NEXT_STAY set to false.

Removing stale mob branches is not yet supported except via mob reset, which is no fit here.

A mob cleanup or mob clean might be added to remove stale branches and, by chance, when on a stale branch, switch to the base branch.

**Comment by simonharrer** [comment]
In summary: let’s add a clean command.

**Comment by simonharrer** [comment]
@koeberlue would you like to have a go at implementing this feature?

**Comment by koeberlue** [comment]
I would love to, but I won't find the necessary time in the foreseeable future. So if someone else wants to implement this, I don't want to stand in the way ;)

**Comment by simonharrer** [comment]
Did a rough implementation just now. Feel free to comment on it.
