### ISSUE TITLE
Feature request: Add Co-authored-by commit message when 'mob done'

### ISSUE THREAD

**Issue by tinolazreg** [remotemobprogramming/mob#250]
It would be a really nice feature if 'mob done' command could create a commit with "Co-authored-by: author-name <name@xxx.com>", including all the authors that had commits on the mob-branch.

**Comment by hollesse** [comment]
I’m not sure how this should work as mob tool does not do the commit on mob done. One thing I have in my is to print a list of all authors except for the one who does the mob done command, such that you could just copy it for the commit message.

**Comment by simonharrer** [comment]
@tinolazreg after you did a `mob done`, when you do a `git commit` without a message, your editor should open, and at the end of the opened file, the co author statements are added. Does this already help you?

**Comment by tinolazreg** [comment]
> 

Wow, I didn't know that the co-author statements were added automatically after doing `mob done`. Thanks a lot, thats exactly what we wanted.

**Comment by simonharrer** [comment]
It reads to me that the existing feature already suffices. If I am mistaken, feel free to repon the issue @tinolazreg

**Comment by erikkrieg** [comment]
Hey, so I'm just trying this out for the first time and went through this sequence of commands to close up a pairing session and I'm not finding any co-authors included.

```sh
mob done
git checkout -b $NEW_BRANCH
git commit
```

I'm then seeing this template:

```

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch initial-engine-add
# Changes to be committed:
#	modified:   <REDACT>
#	modified:   <REDACT>
#	modified:   <REDACT>
#	modified:   <REDACT>
#	new file:   <REDACT>
#	new file:   <REDACT>
#
```

Is this because I checked out a new branch before committing? Or has anyone else had issues with this?

**Comment by gregorriegler** [comment]
Hi @erikkrieg 
mob.sh is using the SQUASH_MSG to consolidate all wip commits, and create the list of the Co-Authors.
I don't think a `git checkout -b $NEW_BRANCH` would cause this SQUASH_MSG to disappear.

If you expected git commit to show the SQUASH_MSG contents, but it didn't, there are several possible reasons why this might happen:

- Squash Operation Not Initiated: The SQUASH_MSG file is specifically created during certain Git operations like squash merges or interactive rebases where multiple commits are being combined into one. If such an operation was not initiated or completed correctly, the SQUASH_MSG file may not be created or used. Did you do a `mob done --no-squash` or `mob done --squash-wip` ?

- Editor Configuration: The default editor configured for Git might not be properly set up to open the SQUASH_MSG file. Check your Git configuration (git config --global -e) to see which editor is set as default and ensure it's properly configured.

- Interruption in Squash Process: If the squash process or interactive rebase was interrupted or not properly completed, the SQUASH_MSG might not be used as expected.

- Environment Variables: Certain environment variables can affect how Git commands operate. For example, GIT_EDITOR, EDITOR, and VISUAL can dictate which editor is used by Git.

- IDE or GUI Tool Behavior: If you're using an IDE or a GUI tool for Git operations, their behavior might differ from the standard Git command-line interface, as they might handle commit messages and squash operations in their own way.
