### ISSUE TITLE
mob clean fails for mob participants 

### ISSUE THREAD

**Issue by jdrst** [remotemobprogramming/mob#259]
if you run `mob clean` as a participant after someone else finishes the session, the command fails.

```
mob clean
git fetch origin
> Removing orphan wip branch mob/main
ERROR git branch -d mob/main
ERROR error: The branch 'mob/main' is not fully merged.
ERROR If you are sure you want to delete it, run 'git branch -D mob/main'.
ERROR exit status 1
```

**Comment by simonharrer** [comment]
Thanks for reporting. Can you tell me how such a situation happened? I’d like to learn why this happens, and have a test to reproduce the issue. Your fix will work nonetheless, but I want to use this as a learning opportunity for me.

**Comment by jdrst** [comment]
Sure. Here you go:

**A**>mob start
**A**>_do work..._
**A**>mob next
**B**>mob start
**B**>_do work..._
**B**>mob next
**A**>mob start
**A**>_do work..._
**A**>mob done
**B**>mob done **< here**

**Comment by jdrst** [comment]
I do realize now that B probably just had to use "mob done" as well. 
This was a first quick test though, and with a glance at the console output mob gives we intuitively went with "clean" instead of done.

**Comment by simonharrer** [comment]
Both work. But clean is the right one here. Can you add a test to reproduce this in the PR?“, please?
