### ISSUE TITLE
troubles with say on ubuntu due to exit code = 1

### ISSUE THREAD

**Issue by enolive** [remotemobprogramming/mob#26]
Using the default voice command "say" from gnustep-gui-runtime results in a strange behaviour on my Ubuntu 18.04 machine. Instead of displaying desktop notifications via notify-send, the notification script ends after saying "Mob Next".

After some analysis I found out that say is at fault. Instead of returning exit code 0  (as it is working) it returns 1.

Show case:

```shell
say "Hello, World!" || echo "Fail!"
```

My workaround is to install an alternative speech engine (espeak-ng-espeak produces better sound anyway) . Either by setting the environment variable MOB_VOICE_COMMAND or even better, by writing a wrapper called `say` (which allows me to use other voice files):

```shell
#!/bin/sh
# please install espeak-ng-espeak and mbrola-us-1 for this to work!
espeak -v us-mbrola-1 "$@"
```

**Comment by simonharrer** [comment]
Not sure what to do here. 

Options:
- swap the order of the commands, so that the return value doesn't matter anymore
- ignore that strange behavior of say on ubuntu
- detect ubuntu and use espeak instead

Anything else I forgot?

**Comment by enolive** [comment]
I'd suggest that you swap the order.
I believe the say command is a nice to have and the desktop notification a little bit more important

**Comment by simonharrer** [comment]
Okay, lets try that.

**Comment by simonharrer** [comment]
Will always execute both commands, regardless of any return status code (using || instead of &&).
