### ISSUE TITLE
Possible issue with mob_v3.1.3_windows_amd64.tar.gz - checksum does not match, corporate tools labels as malware

### ISSUE THREAD

**Issue by TeresaBinks** [remotemobprogramming/mob#267]
I've just tried to help a user install mob on a Windows machine, using both GitBash and PowerShell to run Scoop. 
When using scoop, we are told that the checksum for the downloaded file does not match. 
When I investigate the tar.gz for v3.1.3 in the browser, our corporate tooling (Symantec) prevents me from listing the contents in the browser because it detects malware. 
This doesn't happen for v3.1.2 etc.

**Comment by simonharrer** [comment]
Hm, from the release side, everything looks fine.

```
$ shasum -a 256 mob_v3.1.3_windows_amd64.tar.gz
a0a8c98390c7b63e852ecc400d13359e563eff5a1bf2c58ae469f37292ce2063  mob_v3.1.3_windows_amd64.tar.gz

$ cat mob_v3.1.3_windows_amd64_sha256_checksum.txt
a0a8c98390c7b63e852ecc400d13359e563eff5a1bf2c58ae469f37292ce2063 
```

Also, the v3.1.2 release only lived a few minutes, and was superseded by the v3.1.3 release just a few minutes later.

Looking at https://github.com/ScoopInstaller/Main/blob/master/bucket/mob.json seems fine with the right hash.

I'm feeling out of ideas...

**Comment by simonharrer** [comment]
The file has 3.5MB and in your snippet it shows only 17.7 kb.

**Comment by simonharrer** [comment]
@TeresaBinks What happens when you download the tar.gz file manually on your machine, with something like wget?

**Comment by mightyiam** [comment]
Is there a security issue?

**Comment by simonharrer** [comment]
The checksums for the files on github are fine. So downloading and installing from GitHub is fine. 

Can someone reproduce this with scoop on a Windows machine?

**Comment by TeresaBinks** [comment]
Happy for this to be closed as non-reproduceable. It might be something our end. There is a workaround of installing n-1 if anyone else stumbles over this thread if they encounter the issue.
Thank you very much for looking into it!
