### ISSUE TITLE
Handover Focus

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#28]
# Problem

Handover includes handing over code but also the current focus. The current focus typically is the opened file, and maybe even the cursor position. Maybe also all opened files in the project. 

# Solution Idea for handover opened file

We can get the title of intellij window on osx via 

```bash
osascript -e "tell application \"System Events\" to get the title of first window of process \"idea\""
```

From the title, we can deduct the last opened file. On `mob next`, we can put the filename in the commit message of the WIP commit. And on the next `mob start` we can look for a file with that name and open it. 

Challenges
- two files with same name needs to be resolved somehow
- other operating systems require additional logic to get the window title, and the filename must be shown in the window title
- getting opened file and opening file requires knowledge of editor, and requires editor to be available on the terminal

Any thoughts on this? Not sure whether this is worth it, but found the idea interesting to think about at least.

**Comment by Morl99** [comment]
Maybe it would be a start, to open the file(s) that were modified last? While that surely is not 100% accurate, it could be worth a try. Implementing it isn't editor specific (at least the detection mechanism) and there could be a config setting to control the time span of files (last 60 seconds before mob next for example).

**Comment by simonharrer** [comment]
Thanks for the great idea. Do I understand correctly that you would determine the last modified timestamps of any files changed as the first step when entering 'mob next' and then we could add that file to the commit message so that the next person doing 'mob start' could open that file explicitly?

What do you mean be controlling the time span of files? Can you elaborate that, please?

**Comment by Morl99** [comment]
Right, let me try to sort out the ideas I had in mind.

The simplest thing would be, to determine the youngest file during `mob next` and write it to the commit message.
I can think of two additions:
1. Instead of just a single file, you could find the files modified in the last X minutes (configurable). And write the array of files to the commit message.
2. This would be something for an IDE plugin. If we choose a parseable message format, an IDE plugin could pick it up and make sure that the file is open and has focus. 

Does that make sense?

**Comment by simonharrer** [comment]
Format of the git commit message:

```
mob next [ci-skip]
path-to-file-within-git-repo#line,column
path-to-file2-within-git-repo#line,column
```

Paths sorted by last modified desc.

**Comment by simonharrer** [comment]
Not sure if we should put this on hold. It doesn't make that much sense with the CLI alone, only in combination with an IDE. And the IDE plugins aren't there yet.

**Comment by simonharrer** [comment]
Putting on hold.
