### ISSUE TITLE
`mob done --squash-wip` fails when there are local changes

### ISSUE THREAD

**Issue by mwnciau** [remotemobprogramming/mob#300]
If you have made any changes since running `mob start` and try to run `mob done --squash-wip`, the command will fail. This is inconsistent with `mob done --squash` and `mob done --no-squash`.

## Version

v3.1.5

## Steps to reproduce

```
mob start 10
echo 'abc' >> test.txt
git add test.txt
git commit -m 'add abc'
echo 'def' >> test.txt
mob done --squash-wip
```

## Result

```
rewriting history of 'mob/mobtest': squashing wip commits while keeping manual commits.
ERROR git rebase --interactive --keep-empty d8946dc68ceb4b134fff43839209e464ef234281
ERROR error: cannot rebase: You have unstaged changes.
ERROR error: Please commit or stash them.
ERROR exit status 1
```

## Expected behaviour

The "add abc" commit is added to the original branch, and the addition of 'def' to text.txt is an unstaged change.

You can workaround this issue by running `mob next` before `mob done --squash-wip`, but I would expect the command to automatically handle this.

**Comment by gregorriegler** [comment]
Yes, this only happens if you modified a previously committed file, but didn't commit that modification.
Then you can't rebase. Didn't happen on my computer at first, because I had turned on autoStash in my git config.

**Comment by simonharrer** [comment]
Is autostash the right solution? Or would we do a `mob next` internally and then start the rebase process instead?

**Comment by gregorriegler** [comment]
Do you see a Problem? It's simple. I don't know.

**Comment by simonharrer** [comment]
Merged PR. Will be part of the next release.
