### ISSUE TITLE
mob start does not work on git repository without commits

### ISSUE THREAD

**Issue by JanMeier1337** [remotemobprogramming/mob#303]
When you clone an empty repository from git and want to start working on it the mob tool throws an error:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/48482008/187236905-7cc87c4f-a48a-4017-a641-1725f6e54ae5.png">

Currently I do not have a clue what a proper fix for that would be, since the mob tool would need to create a commit which is not developer made to create the corresponding branches.

Maybe it is not worth the effort investigating that.

**Comment by simonharrer** [comment]
We can’t really do anything here to fix this. A repo without commits cannot create branches from nothing. We could add a better error message though. Care to create a PR for that?

**Comment by JanMeier1337** [comment]
Yes, I will add a detection on an empty git repository, I have some ideas for that. I will create a PR.
