### ISSUE TITLE
add mob to Hacktoberfest 2022

### ISSUE THREAD

**Issue by hollesse** [remotemobprogramming/mob#309]
I just want to have a discussion if it makes sense, that mob praticipates at the Hacktoberfest. We could find some people who are interested in open source development. But we then would need some new ideas for the mob tool, which we create issues for and tag them.
[Here](https://hacktoberfest.com/participation/#maintainers) are more informations what maintainers need to do for participating at Hacktoberfest.

What do you think @gregorriegler

**Comment by gregorriegler** [comment]
Sure, why not.

**Comment by hollesse** [comment]
Then I'll add the topic `hacktoberfest` to mob and add the label `hacktoberfest` to some issues. If you have some issues which could be tackled just add it.
