### ISSUE TITLE
Current install process does not work on Windows

### ISSUE THREAD

**Issue by dannydwarren** [remotemobprogramming/mob#31]
The `curl -sL install.mob.sh | sh` install command does not work on Windows whether in PowerShell or GitBash. The old instructions for Windows were also incomplete:

```
### Windows

- Install [Golang](https://golang.org/): Download and execute MSI from Download page
- Open console and execute following commands

bash
> git clone https://github.com/remotemobprogramming/mob
> cd mob
> .\install.cmd
# Now, you can use the mob tool from anywhere directory in the terminal
```

^ Is a good start, but mob.exe is not correctly added to the PATH so it cannot be found. So these instructions plus a note about manually updating the PATH would be better.

**Comment by simonharrer** [comment]
Git Bash should work, in general, because /usr/local/bin should be available and in the PATH. Can you post the error message here, please?

**Comment by dannydwarren** [comment]
The error with `curl -sL install.mob.sh | sh` was that the command didn't have permission to modify `/usr/local/bin`.

I was corrected by a teammate about the .\install.cmd which does set the PATH correctly.

**Comment by simonharrer** [comment]
If you have WSL (or in a few weeks/months WSL2) the command `curl -sL install.mob.sh | sh` works as well. 

We're currently trying to get it working in Git Bash. 

Looking for contributors for a cmd script similar to the install.sh script.

**Comment by enolive** [comment]
I created a wip branch for handling this issue on windows. 
https://github.com/remotemobprogramming/mob/pull/33

unfortunately, I am not able to fully test it as my windows environment is behind a "firewall of death" so consider it as WIP.
feel free to try it out and give us some feedback!

**Comment by simonharrer** [comment]
Installation in git bash should now work on windows. Merge requests #33 is merged. Can the issue be closed now, or do you expect more?

**Comment by simonharrer** [comment]
@dannydwarren is the issue solved for you with the changes above?

**Comment by dannydwarren** [comment]
@simonharrer @enolive This is the result I'm getting in Windows with GitBash:
```
MachineName MINGW64 /c/src
$ curl -sL install.mob.sh | sh
you do not have access rights to /usr/local/bin.

we recommend that you use the --user flag
to install the app into your user binary path C:/Users/<name>/bin

  curl -sL install.mob.sh | sh -s - --user
```

The suggested command with the `--user` flag works great. I think we're good. Thank you so much!

**Comment by simonharrer** [comment]
Now, it works even better on windows. The --user option automatically enables itself, and the path to the mob tool is automatically added to the PATH of the user. Would love feedback on that @dannydwarren
