### ISSUE TITLE
Default WipBranchQualifierSeparator is wrong in `README.md`

### ISSUE THREAD

**Issue by hollesse** [remotemobprogramming/mob#311]
In the README we tell about the `--branch` parameter for mob start and mob reset. There we explain, the following `[--branch|-b <branch-postfix>]       Set wip branch to 'mob/<base-branch>/<branch-postfix>'` The `/` between `<basebranch>` and `<branch-postfix>` is the configuration value if WipBranchQualifierSeparator. But the default value for this is not `/` it is `-`. So the example in the `README.md` is wrong.

**Comment by YashPimple** [comment]
@hollesse can you assign it to me would like to work on this issue?

**Comment by hollesse** [comment]
@rustiever go for it ;)
