### ISSUE TITLE
Remove deprecated Configuration

### ISSUE THREAD

**Issue by hollesse** [remotemobprogramming/mob#315]
As the next release will be a major release we should think about removing the deprecated configuration options, we still have in the code.

**Comment by gregorriegler** [comment]
Also "mob-session" behavior

**Comment by simonharrer** [comment]
Changing the mob-session behavior will destroy compatibility with the intellij mob plugin. And mob-session has not yet been deprecated with a clear upgrade path for the users. And a lot of people have not yet upgraded from master to main. To he honest, I don’t think it is worth the users trouble to remove the mob-session thing for quite some time.

**Comment by hollesse** [comment]
This can be closed correct @gregorriegler ?
