### ISSUE TITLE
Mob binary prints as `bin\mob` on Windows

### ISSUE THREAD

**Issue by gregorriegler** [remotemobprogramming/mob#322]
As the title suggests, when the mob binary is printed on a windows system, it reads as `bin/mob` which is incorrect.
Running  `bin/mob` does not work. It should just say `mob`.

Example output:
```
.. To start, including uncommitted changes, use

  bin\mob start --include-uncommitted-changes
```
When you copy the full command and execute it, it won't work.

**Comment by balintf** [comment]
I have checked this issue on Windows, and it is due to the `currentCliName` function not handling Windows path separators correctly. I'll send a PR with the fix.
