### ISSUE TITLE
Tests don't work on Windows because of `mobExecutable()`

### ISSUE THREAD

**Issue by gregorriegler** [remotemobprogramming/mob#336]
There is test-specific production code that provides `mob` as an executable for the test environment.
The command it uses is not compatible with windows:
[mobExecutable()](https://github.com/remotemobprogramming/mob/blob/ee44f3711e70b4a65a224feb316e00d374c0d9fc/squash_wip.go#L71)
```
func mobExecutable() string {
	if isTestEnvironment() {
		wd, _ := os.Getwd()
		return "cd " + wd + " && go run $(ls -1 ./*.go | grep -v _test.go)"
	} else {
		return "mob"
	}
}
```

Q: Why have this command in the first place?
A: mob functions as a `GIT_SEQUENCE_EDITOR` for the squash-wip feature. This is why we have to run mob in order to test squash-wip.
See: https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt-sequenceeditor

One Idea would be to add an if clause for windows.

**Comment by balintf** [comment]
I can confirm that `isTestEnvironment ` is indeed incorrect on Windows, I could use the previously implemented `currentCliName` helper function to determine the executable base name. That should fix the `.exe` trimming. Could you assign this issue to me?

There are other problems with the testsuite on Windows. Most notably I get a lot of symlink creation related errors. I'll investigate it a bit more and create a separate ticket for it.

**Comment by hollesse** [comment]
Thank you for investigating! I assign the ticket to you :)
