### ISSUE TITLE
Move to .adoc for the README

### ISSUE THREAD

**Issue by enolive** [remotemobprogramming/mob#34]
while GitHub-flavoured markdown is not bad, specifying the documentation in [AsciiDoctor](https://asciidoctor.org/) would have some benefits:

* creating a table of contents (my main reason for suggesting it as the README is rather long and I love ToCs :wink:)
* figures
* defintion lists
* rich tables
* ...

AsciiDoctor is mostly compatible to Markdown so everyone able to edit Markdown should be able to learing editing AsciiDoctor as well.
GitHub fully supports AsciiDoctor and will render its contents as it would with Markdown.

There is also a way to automatically [convert md to adoc](https://stackoverflow.com/questions/7323596/is-there-any-way-to-convert-markdown-to-asciidoc-or-be-able-to-produce-the-same#13198265)

As of now, GitHub Pages does not automatically support AsciiDoctor ([the jekyll plugin is not white-listed](https://webapps.stackexchange.com/questions/114606/can-github-pages-render-asciidoc)) so additional steps are needed to push the static content to GitHub Pages such as calling Jekyll by yourself and publish it to Pages through GitHub Actions.

**Comment by simonharrer** [comment]
I don’t see the benefit in comparison to the effort and the higher complexity (asciidoc is different to md, github actions, separate github pages branch, ...).

**Comment by enolive** [comment]
I believe that the only benefit would be to have an auto-generated toc. If you feel that this is not important enough, feel free to close this issue.
