### ISSUE TITLE
Mob start timer starts timer with zero minutes if you add a parameter which is not a number

### ISSUE THREAD

**Issue by hollesse** [remotemobprogramming/mob#344]
When I do `mob timer notanumber` this will start a timer with 0 Minutes and directly say `mob next`. This behavior also applies to `mob start notanumber`. 

In my opinion it should work like this:

## `mob timer notanumber` 
- should fail with an error message

## `mob start notanumber``
- If the configuration `MOB_TIMER` is set, this value should be used instead and a warning should be printed
- if configuration `MOB_TIMER` is not set, a warning should be printed

## `mob start` and `MOB_TIMER="notanumber"`
- a warning should be printed

@simonharrer please add your feedback!

**Comment by simonharrer** [comment]
No strong opinion here. It’s okay I guess.

**Comment by gregorriegler** [comment]
I agree with everything but using an existing `MOB_TIMER` setting on `mob start notanumber`.
When somebody write `notanumber` as a command I assume they tried to use this number, but made a mistake typing it.
In that case, using `MOB_TIMER` would not be what they intended to do.

**Comment by hollesse** [comment]
fixed with #416
