### ISSUE TITLE
mob reset could delete the local branch without a warning

### ISSUE THREAD

**Issue by Morl99** [remotemobprogramming/mob#347]
The warning in https://github.com/remotemobprogramming/mob/issues/298 is great to avoid losing all the changes in a mob branch unintentionally. But I had a couple of cases, where it really bugs me, that there is no easy way to remove my local mob branch and switch back to the base branch. I am talking about the following scenario:

- Dev A,B and C work on a mob branch: `mob/great-feature` (base branch is `great-feature`)
- All devs have the mob branch checked out (as it is the case if each dev has contributed to the mob)
- Dev B performs a `mob done`, Dev B is not back to the base branch.
- Dev A and C also want to go back to the base branch, but they are stuck on the mob branch, that doesn't still exist.

I can think of two alternative solutions for this problem:

1. `mob reset` always resets the local mob branch and switches back to the base branch. It prints a message after the deletion, that the remote branch is not deleted, unless `mob reset  --delete-remote-wip-branch` is executed

1. `mob reset` checks, if there is a current mob remote branch (fetching first). If so, it keeps the current behaviour, if not, it just deletes the local mob branch and switches back.

Let me know what you think of this. Given the time, I could also work on this issue, once we have agreed on a potential solution.

**Comment by hollesse** [comment]
If I understood you correctly Dev A and C want to get rid of the mob branch which is just on their local machine an not in remote anymore as this branch was deleted there by doing `mob done`. 

If this is correct the way to go is that Dev A and C do a `mob clean`. This should remove the mob branch and switch to the base branch if it exists. If not it switches to `main`.

**Comment by Morl99** [comment]
Ah, that is a nice one, and we all missed, that this command exists. It might be worth to mention on the readme then? That is exactly what we want, thanks for the pointer.

We could either close this issue, or decide to work on the docs for this use case.

**Comment by simonharrer** [comment]
`mob clean` does more than that, as it does a `git fetch` and then removes **all orphaned wip branches** available, not just the one you are currently on.

**Comment by hollesse** [comment]
I close this as I adjusted the documentation and help.
