### ISSUE TITLE
Fail to sign commit with gpg when using mob next

### ISSUE THREAD

**Issue by QuentinLemCode** [remotemobprogramming/mob#349]
Hello

I have an issue when using mob next : 
````
$mob next
  git add --all
ERROR git commit --message mob next [ci-skip] [ci skip] [skip ci]
ERROR 
ERROR lastFile:app/models/scheduling_task_stats.rb --no-verify
ERROR error: gpg failed to sign the data
ERROR fatal: failed to write commit object
ERROR exit status 128
````

Git repo is configured with `user.signingkey` and `commit.gpgsign=true`

Ubuntu 22.04
Mob has been installed with snap

**Comment by simonharrer** [comment]
This doesn't work because `snap` has a very strict security model. This is known, and that's why snap is only an experimental distribution channel of the mob tool.

If you install mob without snap, it will work as expected.
