### ISSUE TITLE
The published package of version 4.1.2 for MS-Windows triggers virus scanners

### ISSUE THREAD

**Issue by arkascha** [remotemobprogramming/mob#359]
The published package of version 4.1.2 for MS-Windows triggers an alarm in at least two standard virus scanners known to me. This is independent of _how_ the package gets installed, via the choco package manager as recommended in the docu or by manually downloading and unpacking. 
Version 4.1.1 does not show the same issue. 

We are still investigating if this is a false positive or if that package really has been infected.

**Comment by hollesse** [comment]
See also #357

**Comment by hollesse** [comment]
close this one as duplicate
