### ISSUE TITLE
Empty commit message for skip CI is hardcoded - breaks 'mob start' depending on push rule

### ISSUE THREAD

**Issue by t1murl** [remotemobprogramming/mob#363]
Hi all,

First of all thanks for the nice tool! I really enjoy using it for remote mob programming sessions.

With [4.2.0](https://github.com/remotemobprogramming/mob/releases/tag/v4.2.0), #353 has been released. On start of a mob session, this creates an empty commit to skip CI for the new branch.
Unfortunately, this breaks scenarios where certain [push rules](https://docs.gitlab.com/ee/user/project/repository/push_rules.html#validate-commit-messages) are enforced due to the fact that the commit message is hardcoded here: https://github.com/remotemobprogramming/mob/blob/fcd1f6330ae537ea9942aa98eb1e66702bcca736/configuration/configuration.go#L18

Due to this, we can not upgrade to 4.2.0 - or am I missing a configuration option to either disable this (not preferred - skipping CI makes sense here imho) or change the commit message?

I'd like to suggest aligning this with the implementation of the configuration option 'MOB_WIP_COMMIT_MESSAGE': https://github.com/remotemobprogramming/mob/blob/fcd1f6330ae537ea9942aa98eb1e66702bcca736/configuration/configuration.go#L414

Thanks!

**Comment by hollesse** [comment]
Do I understand correctly that you would like to modify the `StartCISkipCommitMessage` via env variables or `.mob` file or do you want to use the `MOB_WIP_COMMIT_MESSAGE` instead of `StartCISkipCommitMessage`?

**Comment by t1murl** [comment]
Hi @gregorriegler , thanks for your reply. Sorry for the missing context in the original description, I am referring to [Gitlab push rules](https://docs.gitlab.com/ee/user/project/repository/push_rules.html#validate-commit-messages) that allow enforcing commit messages to adhere to a regex through a pre-receive git hook. We use those to force ourselves to adhere to using e.g. conventional commit messages.

**Comment by t1murl** [comment]
> Do I understand correctly that you would like to modify the `StartCISkipCommitMessage` via env variables or `.mob` file or do you want to use the `MOB_WIP_COMMIT_MESSAGE` instead of `StartCISkipCommitMessage`?

Sorry I replied on mobile and didn't see your message.

Yes! I'd be fine either way. However, modifying it via `.mob` file sounds like a good idea 🙂

**Comment by lucas-dclrcq** [comment]
Hi,

This is a common issue with gitlab push rules. Push rules are enforced across all branches, you cannot add an exception for branches starting with mob/.

So it would indeed be very nice to be able to configure the `StartCISkipCommitMessage` so the push of a mob branch is not rejected by gitlab push rules.

**Comment by neiser** [comment]
@gregorriegler @lucas-dclrcq Thank you for providing the fix and releasing it so quickly. That saves today's mob programming session!

**Comment by t1murl** [comment]
Thanks also from me @gregorriegler @lucas-dclrcq, really appreciate the quick fix & release! 🙂

**Comment by gregorriegler** [comment]
and also thank @hollesse who reviewed the code and made the actual release 🫶

**Comment by hollesse** [comment]
You are welcome 💜
