### ISSUE TITLE
missing sha in Arch PKGBUILD in v4.4.3

### ISSUE THREAD

**Issue by draptik** [remotemobprogramming/mob#392]
Just a heads up that the arch package version 4.4.3 doesn't have a sha value assigned and therefore can't be installed using the package manager.

```sh
$ cat ~/.cache/yay/mobsh-bin/PKGBUILD

# Where to file issues: https://github.com/remotemobprogramming/mob/issues

pkgname=mobsh-bin
pkgver=4.4.3
pkgrel=1
pkgdesc="Fast git handover with mob"
arch=('x86_64')
url="https://github.com/remotemobprogramming/mob"
license=('MIT')
depends=("git")
optdepends=('espeak-ng-espeak: Multi-lingual software speech synthesizer'
            'mbrola-voices-us1: An American English female voice for the MBROLA synthesizer')
provides=('mobsh')
conflicts=('mobsh' 'mob')

source_x86_64=("$url/releases/download/v4.4.3/mob_v4.4.3_linux_amd64.tar.gz")
sha256sums_x86_64=("")

package() {
    install -D -m644 "LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
    install -D -m755 "mob" "$pkgdir/usr/bin/mob"
}
```
As you can see, the line

```sh
sha256sums_x86_64=("")
```
has no value.

I'm guessing something changed making the following line invalid somehow: 

https://github.com/remotemobprogramming/mob/blob/55c9e90aa77f3d7f0b62e5704ffb556e49e8dd57/.github/workflows/release.yaml#L110

The previous version (v4.4.2) did not have this issue.

**Comment by hollesse** [comment]
I think it could be that we missed something when we changes how to set the output. Maybe there is also a change in how to query it correctly where we missed an adjustment in 33dc54f

**Comment by draptik** [comment]
@hollesse thanks for the quick response!
Testing different environments in CI is always challenging, I feel your pain ;-)
If you need further information/feedback from me (an Arch user): don't hesitate to contact me!

**Comment by hollesse** [comment]
Should be fixed with [2b00b8f](https://github.com/remotemobprogramming/mob/commit/2b00b8fd3d1a13d6e5adf3f68260c2286abc3366). I now thinking if it makes sense to rerun the release pipeline or just wait fir the next release. What do you think @draptik ?

**Comment by draptik** [comment]
@hollesse it's probably easier to wait for the next release, because the AUR policy suggests creating a new patchlevel release for things like this. 
Especially since I am the only one who noticed this... ;-) (I don't mind waiting for the next release)

Thanks for the quick fix!

**Comment by hollesse** [comment]
Okay then I will just wait for the next release.
