### ISSUE TITLE
Exits with 0 on at least some failures

### ISSUE THREAD

**Issue by mightyiam** [remotemobprogramming/mob#402]
Here's one: `cannot start; clean working tree required`

But exits with 0.

**Comment by seanpoulter** [comment]
It looks like we catch that `err` here but don't `exit(1)`:

https://github.com/remotemobprogramming/mob/blob/211588323b167d9d584a23e900ddd534a5f8f4ba/mob.go#L309-L311

Would that be an appropriate change, or do we have a different plan to handle exit on error?

**Comment by hollesse** [comment]
Hi @seanpoulter `exit(1)` is the way to go! Would you like to create a pull request for that?

**Comment by seanpoulter** [comment]
I'm happy to make a PR @hollesse.
