### ISSUE TITLE
Remove cancellation of the local mob timer when doing mob done or mob next

### ISSUE THREAD

**Issue by hollesse** [remotemobprogramming/mob#406]
We should remove this feature for the following reasons:

- If you switch from one codebase to another the timer gets stopped and a new timer will start. This could lead to longer rotation times
- the way we stop the timer is just searching for the right process and killing it. This is a behavior which is suspicious for the most virus detection applications and could be one cause why mob is listed for some virus detection tools in windows. (see #357)

**Comment by gregorriegler** [comment]
released this, but still 5 detections on VirusTotal

https://www.virustotal.com/gui/file/f99be56a77f7a5c34cbff20bc3693344dc67917229ba89d9dace7ac0cded8b54?nocache=1

**Comment by hollesse** [comment]
@gregorriegler I knew. I tested it before on virustotal. But if you have a look at the behavior analysis then it looks at least a bit better. I think this is a problem which has emerged and therefore we need to look at different points where we need to adjust. And this is just one point.
