### ISSUE TITLE
Feature request: Command to show all open current mob branches

### ISSUE THREAD

**Issue by programmiri** [remotemobprogramming/mob#438]
# Description 

As a user I want to do e.g. 

- 'mob branch --show'

And see a list of open mob branches I could join.

#SoCraTes2024 ❤️

**Comment by programmiri** [comment]
Hi @simonharrer  thanks for the quick check! Took a look and I feel `mob branch` is what was needed 🎉  (I wrote the ticket down during our session at SoCraTes)

**Comment by hollesse** [comment]
I will close this issue as you said @simonharrer's suggestion is what you was looking for @programmiri
