### ISSUE TITLE
Break - break duaration in minutes isn't parsed correctly

### ISSUE THREAD

**Issue by plejd-sebman** [remotemobprogramming/mob#441]
system: MacOS
version: v5.1.0
shell: zsh
command: "mob break 5" after running "mob start 25"
error msg: ERROR The parameter must be an integer number greater then zero

**Comment by hollesse** [comment]
Hi @plejd-sebman,
thank you for reporting this bug! I found the issue and will release a bug fix :)

**Comment by plejd-sebman** [comment]
So happy that you've picked it up. Thanks for a perfect tool serving us very well in our day-to-day jobs.
