### ISSUE TITLE
automated homebrew release

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#49]
Currently, releasing a new version of mob with homebrew is a manual process. I'd like this process to be fully automated using GitHub actions.

**Comment by Morl99** [comment]
I did some research, and this looks straight forward There is a ready to use action, but is marked as experimental, and it uses a template file for the formula. I am not sure what the benefit of that is

I think I would follow this approach: https://medium.com/@Extrawurst/github-actions-homebrew-%EF%B8%8F-2789ae5023fd

I might just give it a try. Before merging, you would need to generate a token that has access to the tap repository, but that seems quite obvious.

Does that sound like a good approach?

**Comment by simonharrer** [comment]
Sounds great. Would really make maintaining this library much easier if the homebrew info would be kept up to date automatically for each new release. 

The repo is part of the orga: https://github.com/remotemobprogramming/homebrew-brew Maybe access is possible without a special token?

**Comment by simonharrer** [comment]
And I agree, following the approach of that medium article seems the easiest road here.

**Comment by Morl99** [comment]
You definitely need another secret, the default GITHUB_TOKEN is limited to the single repo it is contained in, see https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token for details. 

I am not sure when I will find the time to set this up, it might take a few days. If anybody else wants to pick up the ball, go ahead.

**Comment by simonharrer** [comment]
I've created the secret HOMEBREW. You should be able to access it via `${{ secrets.HOMEBREW }}` in the workflow yamls. I hope I got the permissions right. If not, please ping again.

**Comment by Morl99** [comment]
Okay, I think I got it. I did quite a few changes to the release workflow. Let me try to summarise:

1. I refactored the existing workflow to use a matrix strategy to avoid copy and paste for different operating system targets
2. I included the go tests, I needed to copy and paste the git config for homebrew anyways, so copy&pasting the go test line did not seem to hurt so much. That means, that the release will inevitably fail if the tests fail, but the release is actually already created. While this is not ideal, it is still better than to release a version that has failing tests. This is more a safeguard, you should still run the tests before creating the release.
3. I followed the homebrew update formula approach from the medium blog article. This means, that the formula will not really be updated automatically, but a pull requests is created, which still has to be merged. If you want, I assume that with the token we already have, we could use the github api to merge the pull requests automatically. Let me know if you want to pursue this.
4. I fixed the fact, that the workflow actions got triggered thrice for each release, on create, release and publish. 

I set up my personal org to test this, so I created https://github.com/Morl99/homebrew-brew and also created the secret HOMEBREW. This all works well, and you can take a look at the pull requests and the released assets if you like to double check. This is the reason why I use variables in the workflow where the org name is needed, as this allows me to test the workflow and merge it back into your repo without modifications.

What do you think?

**Comment by simonharrer** [comment]
Awesome. Let's start with automatically creating a PR. Can I merge this already?

**Comment by Morl99** [comment]
yes, go ahead!

**Comment by Morl99** [comment]
Maybe a better way to move forward after merging this is to add mob to homebrew-core, then the PR would be the correct approach (PR to homebrew-core). Let us create a new issue for that.
