### ISSUE TITLE
Platform independent Timer

### ISSUE THREAD

**Issue by stritti** [remotemobprogramming/mob#5]
https://github.com/blang/thymer could be integrated to be platform independent.

**Comment by stritti** [comment]
I am not familiar in Go, but will try this ...

**Comment by stritti** [comment]
Looking forward your review

**Comment by simonharrer** [comment]
Hm, I don't like having so much complex code in the CLI tool. It should interact with existing tools if they are available on the system. That's kind of how I envisioned the tool. Can I interact with an already installed version of thymer on the system?

**Comment by stritti** [comment]
Hi Simon,

I am with you. The problem is, that there is no adaquate tool on windows and using this solution it will be a unified independent solution. Currently Thymer is not available as library which could do the job easier. And I am not familar to transform it to a lib (I am Go rooky ...)

**Comment by simonharrer** [comment]
I don't have a windows system around, but I think the tool 'at' should be available. Can a timer be done through interfacing with 'at' at the command line?

**Comment by simonharrer** [comment]
Closing this for now. I'm happy to add some code for a timer tool running on windows, though.
