### ISSUE TITLE
superfluous double quotes on commit message with MOB_WIP_COMMIT_MESSAGE

### ISSUE THREAD

**Issue by ddingel** [remotemobprogramming/mob#52]
Current behaviour I observe:
``` 
export MOB_WIP_COMMIT_MESSAGE="MAGIC-JIRA-STUFF tmp"
../mob start 10
``` 
``` 
touch test
``` 
``` 
../mob next
>   git add --all
>   git commit --message "MAGIC-JIRA-STUFF tmp" --no-verify
....
>  ERROR remote: refs/heads/mob-session: 05bc5e5802d97062973fd1a3be48bb9e7a1d91e6: > commit message doesn't match regex: ([A-Z0-9\-]+)\s(?s:.*)
``` 
``` 
git show --oneline
> 05bc5e5 (HEAD -> mob-session) "MAGIC-JIRA-STUFF tmp"
```

I also tried changing 
`export MOB_WIP_COMMIT_MESSAGE="MAGIC-JIRA-STUFF tmp"`
 to:
`export MOB_WIP_COMMIT_MESSAGE='MAGIC-JIRA-STUFF tmp'`
`export MOB_WIP_COMMIT_MESSAGE=MAGIC-JIRA-STUFF\ tmp`

but it all showed me the superfluous double quotes around the commit message subject.
Which will be then rejected because our... tight rules regarding commit message subjects for all branches.

I would expect that what will be placed in MOB_WIP_COMMIT_MESSAGE will be used and not be wrapped in double quotes.

Also I would ask you to please reconsider your intention in this [comment](https://github.com/remotemobprogramming/mob/issues/45#issuecomment-643212643) to remove this option. As I know some companies applying filters to commit message subjects.

**Comment by simonharrer** [comment]
Intention already reconsidered. Thanks for sharing your way of working. Configuration option will be kept!

**Comment by simonharrer** [comment]
Fix already implemented.

**Comment by simonharrer** [comment]
Release with 0.0.23 is out the door with a fix to your issue. Happy remote mob programming! :-)

**Comment by ddingel** [comment]
Just checked the new code... sooo, it is better, but not perfect, as with a space containing string, the flow is:
`export MOB_WIP_COMMIT_MESSAGE="JIRA-MAGIC tmp"`

```mob next
>    git add --all
>   git commit --message JIRA-MAGIC tmp --no-verify
```

resulting in:
```
git show
> f65926c (HEAD -> master, origin/master) JIRA-MAGIC commit
```

1) I am confused where git picked up the "commit" suffix
2) I assume we need some sort of quoting as on the command line you would do something like
`git commit -m "JIRA-MAGIC tmp"`

**Comment by ddingel** [comment]
Some more testing on my side and yip, it does work exactly as it should, perfect!
I mixed up my branches and that also explains that magical JIRA-MAGIC commit things, as I did it some time ago.
Mea culpa.

**Comment by simonharrer** [comment]
No worries. :-) Glad that it works for you now.
