### ISSUE TITLE
script to determine download numbers using github api

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#53]
I would like to know how often 'mob' is downloaded.

The github releases api provides download counts. 

A script that would compute this per release and per platform would be interesting.

**Comment by simonharrer** [comment]
```
curl -s https://api.github.com/repos/remotemobprogramming/mob/releases | jq ".[].assets | .[] | .download_count" mob.json | jq -s 'add'
```

**Comment by Morl99** [comment]
Ok, I know it is not a script, but I wanted to play around with angular and typescript a bit. Here it comes: https://angular-vmrxub.stackblitz.io

**Comment by simonharrer** [comment]
Best would be a badge just stating the total download numbers on https://mob.sh

**Comment by Morl99** [comment]
So is this more like it?

**Comment by simonharrer** [comment]
Awesome. Great and easy solution. :-)
