### ISSUE TITLE
Expand "How to contribute" so that Code Contributions become easier

### ISSUE THREAD

**Issue by Morl99** [remotemobprogramming/mob#57]
I am a go newbie, but I like this project and would like to help out more (if you would accept code contributions). But I struggle to understand the project setup. A short paragraph on how to setup the project as a go developer would be nice. In the end, it should allow to run the tests locally and compile the code. It should also include the Go version used.

**Comment by simonharrer** [comment]
awesome. I’ll write up something tomorrow when I’m back at my computer.

**Comment by simonharrer** [comment]
Does the new infos in the README help?

**Comment by Morl99** [comment]
yep, that is awesome. Now I know, that my intellij setup somehow is the problem. go commandline works fine.

**Comment by simonharrer** [comment]
That's how I run the tests in intellij 
<img width="1064" alt="Screenshot 2020-06-23 at 16 29 51" src="https://user-images.githubusercontent.com/375693/85416496-d0a92f00-b56e-11ea-9081-da7c780ebf3c.png">

**Comment by simonharrer** [comment]
Feel free to reopen when you have more ideas on how I can help out new contributors.
