### ISSUE TITLE
mob start does not work if existing session is in progress and branch contains /

### ISSUE THREAD

**Issue by Morl99** [remotemobprogramming/mob#58]
This is in reference to #56, but i opened a new issue, since part of the #56 issue was fixed in v0.0.24. Find a trace attached, unfortunately this still does not work. 

In #56 I only tested with a new session, which works ok. Now it seems to go wrong when mob tries to find out the latest committers.
[scratch_41.txt](https://github.com/remotemobprogramming/mob/files/4819200/scratch_41.txt)

**Comment by simonharrer** [comment]
Works as expected. You're on branch 'mob/feature/removeDeployersYaml-DPL-2833' and there's no 
 'feature/removeDeployersYaml-DPL-2833' branch. That's what confuses the mob tool.

**Comment by Morl99** [comment]
ahh, that was because of my tests earlier. Thank you! This is a scenario that is otherwise highly unlikely, so we can leave it be.
