### ISSUE TITLE
Have mob next push if there are commits, but no changes

### ISSUE THREAD

**Issue by sjdecaro** [remotemobprogramming/mob#61]
### Problem

During a mob session, one of the developers created a commit while in her session. When she executed `mob next`, she had no additional changes after her last commit. Right now, the `mob next` command skips all `git` commands if no changes are found. So when the next person tried to `mob start`, we couldn't find her work.

### Suggestion

As part of the `mob next` logic, check to see if the local branch is ahead of the remote branch. If so, push to remote.

### Reasoning

We started doing some intermediate commits to have a working state of code to fall back on. This feels like a healthy practice to follow if you get a test working or a refactor completed prior to your session being complete.

If this is not a recommended practice for this tool, that might be helpful to include in the documentation.

**Comment by simonharrer** [comment]
Thanks for helping on improving 'mob'. Really appreciate taking your time in writing up your idea. 

The idea of 'mob' is that it completely controls the wip branch. Have to think about whether it makes sense to deviate from that and support other cases as well.

**Comment by sjdecaro** [comment]
That makes sense, and I totally get that perspective. We didn't really notice speed issues with any of the commands we used, so props there. =)

While I don't want git to cause a latency issue with the handover, our (human) handover was slowed down trying to figure out why our changes were absent. That's why I was hoping for some improved clarity about the proper use of the command, at a minimum (even just "avoid using your normal git commands while using mob" ;) ).

**Comment by simonharrer** [comment]
On second thought, one could locally check if `origin/mob-session` and `mob-session` deviate and only if they point to two different commits initiate a `git push`. This would help you and won't interfere in any other use case.

**Comment by simonharrer** [comment]
Manual commits are pushed now since 0.0.25. 

Please reopen if this doesn't suffice for your use case.
