### ISSUE TITLE
Remove go-release.action from release workflow

### ISSUE THREAD

**Issue by Morl99** [remotemobprogramming/mob#69]
I feel that it would be worth it to get rid of the forked Github Action to release Go artifacts. As of today, all the necessary steps are available as ready to use actions. I would compose them in the following way:
1. setup go in the desired version (https://github.com/actions/setup-go) 
2. run a build
3. upload a release (https://github.com/actions/upload-release-asset)

If you @simonharrer agree, I would prepare a corresponding PR. But maybe I am overlooking a reason to use the custom Action other than legacy?!

**Comment by simonharrer** [comment]
Great idea. Go ahead!
