### ISSUE TITLE
mob next checking out master is confusing

### ISSUE THREAD

**Issue by alexkli** [remotemobprogramming/mob#7]
If you regularly rotate, the fact that `mob next` checks out master can get in the way:

* you get back to a state before the mob session, thereby loosing all the code you have already written in the session (but you might want to look at it on your computer to research something)
* it can confuse any open IDE if any new files are all removed
* if a `.gitignore` was added part of the mob session, then `mob next` removes it, but leaves around whatever is ignored (e.g. a `node_modules` folder), which in turn will make the next `mob start` of the typist fail, as that one does not like any non-added and non-committed files lying around
* if you started from a different branch than master, it's confusing that it does not return to the same one (for a typist who didn't start the first `mob start` and who did not set `MOB_BASE_BRANCH`)

IMO for the typical mob rotation it would be nice if:
* `mob next` commits & pushs but stays in the `mob-session` branch
* the next `mob start` will simply `git pull` the new commits from the `mob-session` branch

**Comment by fatso83** [comment]
Ah, thanks for pointing out `MOB_BASE_BRANCH`! That alerted me to https://github.com/remotemobprogramming/mob/blob/master/mob.go#L13, where it's basically documented how to pass in configuration variables. That possibly makes #8 superfluous, but it's not really documented ...

**Comment by simonharrer** [comment]
Hm, I like the idea. Will think about it. Need to handle stale 'mob-session' branches though, in case the typist ends their day with a mob next and rejoins the mob a week later. The mob-session branch on the master may already be another one, and they no longer match...

**Comment by simonharrer** [comment]
Implemented it in the newest version. Please try it out. :-)

**Comment by alexkli** [comment]
Will try. One suggestion: A cli option like `mob next -k` for keep - or even the default - would be shorter and easier to type. Nobody can remember these long environment variable names :-)

**Comment by simonharrer** [comment]
You can now use `mob -stay next` or `mob -s next`.

**Comment by alexkli** [comment]
Thanks, tested and it works.

But the help is a bit broken now:

```
> mob -h
Usage of mob:
  -s	(shorthand)
  -stay
    	don't change back

> mob --help
Usage of mob:
  -s	(shorthand)
  -stay
    	don't change back
```

Only `mob help` works:

```
> mob help
usage
	mob [s]tart 	# start mobbing as typist
	mob [-s][-stay] [n]ext 	# hand over to next typist
	mob [d]one 	# finish mob session
	mob [r]eset 	# resets any unfinished mob session
	mob status 	# show status of mob session
	mob --help 	# prints this help
	mob --version 	# prints the version

examples
	 mob start 10 	# start session with 10 min.
	 mob next 	# after 10 minutes work ...
	 mob done 	# After the work is done.
```

**Comment by simonharrer** [comment]
Thanks for the hint. I reopen the issue to fix the help.

**Comment by simonharrer** [comment]
Help fixed. Thanks for reporting it again.
