### ISSUE TITLE
Include mob in the official homebrew repository

### ISSUE THREAD

**Issue by Morl99** [remotemobprogramming/mob#70]
It would be nice, if mob was part of the official homebrew repositories, which would make installing mob on mac and linux (with linuxbrew) easier and somebody that hears of the tool ("hey, have you heard of mob, it is a great cli tool for remote mob programmin") could intuitively run `brew install mob`. 

In order to achieve this, the Formula for mob has to be adapted to comply with the [Formula Cookbok](https://docs.brew.sh/Formula-Cookbook). The biggest change in my opinion is, that homebrew/core only allows Formulas which build from source. Binaries are only allowed in cask, but a CLI tool should not really be put into Cask, because it is unnessecary, and in the end, mob really is a tool that works on all platforms. Here is an example: https://github.com/Homebrew/homebrew-core/blob/master/Formula/golang-migrate.rb

After changing the Formula in the described way, it should be enough to fork homebrew/core (acually, the command we use `brew bump-formula-pr` will also create the fork, if it has a GITHUB API TOKEN with sufficient permissions). 

Looking at the examples in the wild, a lot of people write a Makefile for building their Golang app, probably to keep the Formula code as simple as possible. It is also a good practice to write a test, so that the Homebrew CI can check, if the Formula works and produces a valid binary. Any ideas?

**Comment by simonharrer** [comment]
I second having mob in the official homebrew repository. I am open for having a shell script that performs the build to keep the formula clean.

**Comment by simonharrer** [comment]
Currently, the download stats include installs via homebrew. I do like this fact. When in the official homebrew repo, everybody builds locally from source, which makes the download stat less useful. So not sure which way to go is better.

**Comment by Morl99** [comment]
Homebrew does track formula installs though, wouldn't that be enough?

**Comment by simonharrer** [comment]
I see. Would work then. Maybe add a badge for brew installs then as well?

**Comment by simonharrer** [comment]
What's the status on this? Do you plan to help with this? Otherwise, I would put it on hold.

**Comment by simonharrer** [comment]
Putting on hold for now. Please reopen again when work continues.

**Comment by Morl99** [comment]
Sorry for not answering, I lost track of your question.

I think closing is a good idea. I am not really convinced, that the small amount of added value is worth the amount of work. It is already quite easy to install mob on a mac. 

I know that it was my idea, but I guess I had a change of heart :)

**Comment by simonharrer** [comment]
No worries. :-)
