### ISSUE TITLE
Add badge for latest version number to mob.sh

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#72]
I want to see the latest version number of mob as a badge.

**Comment by kakakakakku** [comment]
@simonharrer 
Like this ? 😃

![](https://img.shields.io/badge/mob-v0.0.24-CC00FF.svg?style=plastic) ![](https://img.shields.io/badge/mob-v0.0.24-CC00FF.svg?style=flat) ![](https://img.shields.io/badge/mob-v0.0.24-CC00FF.svg?style=for-the-badge)

- Using Shields.io
    - https://shields.io/
    - Same as an existing badge
-  Purple color `CC00FF` is extracted from mob logo image

Just for reference, thanks 👍

**Comment by simonharrer** [comment]
Awesome. That would be perfect. Can you open a PR for the second badge?

**Comment by kakakakakku** [comment]
Could you review it ?
Many thanks.

**Comment by simonharrer** [comment]
Thanks for your help!

**Comment by kakakakakku** [comment]
Oh, I didn't know `github/v/release` syntax.
Sorry 😢 

```
https://img.shields.io/github/v/release/remotemobprogramming/mob
```

Thank you fix it 👍 Awesome

**Comment by simonharrer** [comment]
no worries, just realized it after a new release.
