### ISSUE TITLE
README Credits section shows some raw tags

### ISSUE THREAD

**Issue by dsm2005** [remotemobprogramming/mob#76]
In the Credits section of the README, as displayed at https://github.com/remotemobprogramming/mob there are some html tags rendered as text.

I'm not sure how to fix those elements, while preserving their intended function.

<img width="941" alt="Screen Shot 2020-07-17 at 7 35 39 PM" src="https://user-images.githubusercontent.com/1200017/87842919-0cc96a00-c865-11ea-8dab-648ab5973578.png">

**Comment by simonharrer** [comment]
Maybe we could move that to a footer jekyll file. The readme is accessible via https://mob.sh

**Comment by simonharrer** [comment]
After some research, I haven’t found a possibility to handle this while keeping the project readme simple. Please reopen if you have a solution.
