### ISSUE TITLE
Defaults read from config file

### ISSUE THREAD

**Issue by fatso83** [remotemobprogramming/mob#8]
We have a `develop` branch as our default, which doesn't work that well with your default. Having a way of having that set as the branch default would remove a bit of manual git work that we have to do today.

A checked in .mobdefault would help :-)

**Comment by simonharrer** [comment]
Hm, I am somewhat reluctant to add support for such files. Environment variables are available to configure the tool. Should work as long as you don't mob together with teams, each having their own "defaults". Not sure this is a typical use case, though.

**Comment by simonharrer** [comment]
Closing it for now. Maybe will reopen it later, if more people have this kind of use case.
