### ISSUE TITLE
Using another branch (not master) as a base branch may lead to problems

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#82]
`mob` works well when used with the master branch. Calling `mob start` on master switches to the wip branch `mob-session`. And calling `mob start --branch=green` on master switches to the wip branch `mob/master/green`. So far so good. 

But it gets problematic when you are on a branch other than master. Let's assume you use `main` instead of `master` for your trunk. Calling `mob start` on main switches to the wip branch `mob/main`. Calling `mob start --branch=green` on main switches to the wip branch `mob/main/green`. So far so good.

Problem is: git doesn't allow a branch named `mob/main` and a branch named `mob/main/green` to coexist. This is because branches are mapped to the filesystem, and on the filesystem, `mob/main` cannot be a file and a directory at the same time. This means for the mob tool that whatever came first (`mob/main` or `mob/main/green`), the other branch cannot be created.

Not sure how to proceed. But I want that mob works well with a `main` branch too. I'm open for ideas.

**Comment by gregorriegler** [comment]
could use another separator. e.g. mob/main-green

**Comment by schmonz** [comment]
Is it the case that running `mob start` on branch `$FOO` switches to branch `mob/$FOO`, for all values of `$FOO` _except_ `master`? If so, which code is treating “master” specially here — `git` or `mob`?

**Comment by simonharrer** [comment]
@schmonz just for historic reasons within the mob tool - nothing to do with git itself. The special handling of „master“ by mob will be removed in future versions.

**Comment by simonharrer** [comment]
@gregorriegler I am wondering what the best separator would be. One dash, two dashes, one underscore, two underscores, or something else? Want to invest in the right one. :-)

**Comment by simonharrer** [comment]
Will probably go with the dash, so `mob/main-green` instead of `mob/main/green` with an environment variable to use the old behaviour if necessary.

**Comment by simonharrer** [comment]
Solution implemented, and will be released in 0.0.27. Here's an excerpt of the planned release notes:

- BREAKING: named wip branches changed format from 'mob/main/green' to 'mob/main-green' because of conflicts that occurred when 'mob/main' was present as well. For previous behavior, set environment variable `MOB_WIP_BRANCH_QUALIFIER_SEPARATOR` to '/' like this: `export MOB_WIP_BRANCH_QUALIFIER_SEPARATOR=/`.

**Comment by simonharrer** [comment]
I chose to make this a little bit slower. I added the environment variable and default it to '/' for now including a update warning. In future versions, this will default to '-'. So the update process is smoother.

**Comment by davidalpert** [comment]
@simonharrer what about making the "main"/"trunk"/"primary"/"base"/etc branch a configuration option. it could default to `main` which is more common these days but be overridden through configuration to match whatever the local repo has.
