### ISSUE TITLE
Avoid unnecessary pull after fetch?

### ISSUE THREAD

**Issue by escodebar** [remotemobprogramming/mob#83]
Hi!

I saw this `git pull`:
https://github.com/remotemobprogramming/mob/blob/43d0aedf0c1f07f394c09afe9654245bac18902f/mob.go#L395

Whis is executed after a `git fetch`:
https://github.com/remotemobprogramming/mob/blob/43d0aedf0c1f07f394c09afe9654245bac18902f/mob.go#L376

Since `git pull` is nothing else than a `git fetch && git merge FETCH_HEAD`, the pull could be replaced with a `git merge --ff-only FETCH_HEAD`.

Is there a reason for the `git pull --ff-only`?

**Comment by simonharrer** [comment]
Cannot think of any. Might be a relic of the past when there was no separat git fetch. Thanks for pointing it out. Interested in opening a PR to fix this?

**Comment by simonharrer** [comment]
Thanks again for reporting. I just had a little bit of time on my hands so I implemented the proposed solution. Hope that's okay with you.
