### ISSUE TITLE
mob not installable/upgradable on MacOS Big Sur

### ISSUE THREAD

**Issue by devpie** [remotemobprogramming/mob#88]
Hi,

maybe it's the wrong place to tell, but the installation/upgrade process with Homebrew does currently not work anymore:
![image](https://user-images.githubusercontent.com/1233285/101333557-08830500-3877-11eb-804c-2bfbef9ddd06.png)

Cheers
Jan

**Comment by simonharrer** [comment]
I've updated both, homebrew and the command line tools (CLT) - then it works.

**Comment by devpie** [comment]
thanks @simonharrer. I also found out about these tasks to fix the problem. :)

**Comment by devpie** [comment]
```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install

```

**Comment by simonharrer** [comment]
Glad that it works for you now! Happy mob programming!
